GSA/calc

- README.md
- api/views.py
In this PR....
- changed small_business param to business_size
- valid values for the new param include s (for small business) or o (for other than small business)
- updated readme
> small_business param is now business_size

- api/tests.py
- api/views.py
- requirements.txt
- Added the filters
- Wrote tests for each filter
- Replaced fixture with object factory to speed up tests
> Added greater than and less than price filtering to API

- hourglass_site/templates/index.html
This PR replaces the single price input with two inputs that set the price minimum and maximum, per [this Trello card](https://trello.com/c/BTJUWhMd/50-basic-price-filter).
> Add price range filters

- api/mommy_recipes.py
- api/tests.py
- api/views.py
This will be a running PR with the test changes. So far:
- Added tests for multi-word queries
- Added tests for education level
- Added tests for min and max experience
> Improve API test coverage

- api/tests.py
- api/views.py
- Added sorting, supports descending order with '-', and multiple sort
columns can be comma-separated.
- Added tests.
> Added sorting to API

- requirements.txt
> Adding django_nose to requirements

- .gitignore
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
This PR moves the inline styles from the index template into their own stylesheet, `index.css`.
> Clean up CSS

- api/views.py
- selenium_tests/tests.py
Taking a stab at a Google-formatted docstring. Comments very welcome. Should we be documenting the query params there, as I did?
> Added docstring for queryset and its filter params AND NEW TESTS! TEST REFACTORING! AND MORE!

- hourglass_site/templates/index.html
- selenium_tests/tests.py
- Also fixed a regression in the filter input names
> Test that price filter is the last

- selenium_tests/tests.py
Tests were all passing under PhantomJS but not the Firefox driver. Does not resolve all issues, but putting in waits more consistently seemed to help. Perhaps there is more lag when not using a headless browser.
> Increasing Selenium test compatibility w/ Firefox

- Makefile
- Added test-backend task
- Added liveserver settings to all test tasks
> Changed Makefile

- Makefile
- api/tests.py
- contracts/models.py
Let's leave this open for now. TODO items include:
> Education level sorting/filtering

- Makefile
- selenium_tests/tests.py
This PR adds very basic Selenium tests for the different query types, and fixes some issues in the Selenium testing code related to checkbox and radio button inputs.
> Tests for query types

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
* convert the experience input from a number input into a text input w/placeholder
* add `$` prefix labels around the min and max price inputs
* add some space around all three inputs
> Input tweaks

- selenium_tests/tests.py
No need to merge this right away... Gonna be adding to it.
> Test cleanup

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/templates/index.html
:construction: **Work in Progress** :construction:
This PR addresses the front end task in [this card](https://trello.com/c/guZTFNjF/20-a-way-to-exclude-individual-outliers-from-search-results). Still to do:
> [WIP] Exclude individual results UI

- hourglass_site/static/hourglass_site/style/index.css
> only show form debug borders in selenium tests

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
> add axis labels, fix #115

- hourglass_site/templates/about.html
- hourglass_site/templates/base.html
- hourglass_site/templates/index.html
WIP :warning: :construction:
This adds an alert message for people using IE8 and older and does not load JS for them. This resolves https://github.com/18F/calc/issues/116
> Add IE8 alert

- Makefile
- hourglass_site/static/hourglass_site/js/index.js
@maya knows what this is all about.
> Fix misnamed function and static collection logic

- hourglass_site/templates/index.html
- selenium_tests/tests.py
This removes the price filter from the optional filters. This is what it looks like:
> Remove price filter

- hourglass_site/static/hourglass_site/js/index.js
Fixes https://github.com/18F/calc/issues/137
> Tooltip on remove links should update

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/templates/index.html
This implements the new filter layout.
> Add filter layout

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/main.css
Adds "years" to the experience cell when hovering over a row.
> "Years" label in table

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
This moves the export button down below the filter.
This is how it looks:
> Move export button below filter

- hourglass/settings.py
- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/index.html
Removes my previous export link href updating as it was duplicate functionality.
Adds the API_HOST into the template href.
> Adding API host into export link

- Procfile
- deploy.md
- hourglass/local_settings.example.py
- hourglass/local_settings.travis.py
- hourglass/settings.py
- manifest.yml
- requirements.txt
This PR includes:
- Updates to the CF manifest to make the names saner
- Updates to the Procfile and requirements to install New Relic monitoring
- Instructions for deploying (deploy.md)
- Updates to settings.py and requirements.txt to force https
> CF Changes, Forced HTTPS

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
This styles the document icon so it matches the link and link hover color. I'm inlining the SVG in order to apply CSS styles.
> Style document icon

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
Adding Proposed Price input and price callout.
> proposed price input

- hourglass_site/static/hourglass_site/js/index.js
Addressing issues #182 and #163
> clear histogram labels on each draw

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/index.html
was an issue with conflicting class. fixes #188
> fix education level field disappearing

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/index.html
> clear search to reset education multiselect and experience slider

- hourglass_site/static/hourglass_site/js/index.js
regarding #198 ... for now it just returns $0 instead of NaN
> display $0 instead of NaN when no results for standard deviation

- deploy.md
- Updating the space names
- Adding in info about continuous deploys
- Fleshing it out more
> Updating deployment docs

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/index.html
> proposed price with decimal support in histogram

- selenium_tests/tests.py
... and leave notes for future devs.
> Remove Selenium tests we can't fix right now

- .about.yml
added the sprint board to the links
> updated about.yml

- hourglass_site/templates/base.html
> update email address

- selenium_tests/tests.py
This is an attempt to help with #266, though I don't feel comfortable saying it actually *fixes* things. It just deals with the symptoms in a more fault-tolerant way.
Basically, it's hard to diagnose what's going wrong in #266. There's a lot of different technologies involved here: a python webdriver client is talking to a ghostdriver-based remote webdriver server embedded in a headless webkit browser, which is talking to a django-based web server. There's a high degree of concurrency, and very little visibility into each component's internal state.
Google searches haven't helped much.
The only thing I *did* manage to determine was that [`selenium.webdriver.remote.webdriver.WebDriver.get()`](http://selenium-python.readthedocs.io/api.html#selenium.webdriver.remote.webdriver.WebDriver.get) …
> Attempt to make selenium tests more reliable

- api/views.py
- requirements.txt
This gets us up to date with the latest version of Django REST framework, which paves the way for #293!
> Upgrade to Django REST framework 3.3.3.

- hourglass/settings.py
#300 was a bit silly. This is way less hacky!
> Don't use globals() when looking up SECRET_KEY.

- README.md
- hourglass/robots.py
- hourglass/settings.py
- hourglass/tests.py
- hourglass/urls.py
> Add ENABLE_SEO_INDEXING setting.

- README.md
This was originally made to test QuantifiedCode PR integration, which didn't work. However, there are some minor valid README modifications here that can be merged.
> Minor README modifications

- meta/management/commands/ultratest.py
This embeds an [ascii logo made from a text to ascii art generator](http://patorjk.com/software/taag/#p=display&f=Big&t=UltraTest) and combines with with some rainbow color code from https://gist.github.com/danielrehn/d2e6f2129e5f853c3166.
> Add rainbow ascii art to ultratest

- hourglass/settings.py
- hourglass/urls.py
- hourglass_site/static/hourglass_site/style/index.css
- requirements.txt
Update CALC with new hourly prices received from Kelly.
Also:
- upgrade Django to newest 1.7 release
- minor styling hotfix since some of the new labor categories have very long names
- remove django.contrib.admin and associated url config since the admin site is unused
> July 2016 Hourly Prices Update

- hourglass_site/static_source/style/components/_buttons.scss
- hourglass_site/static_source/style/components/_formbuttonrow.scss
These are some fixes to the WDS styles.
- remove margin from buttons
- fix references
- change some var names
> Fixes to PR #452

- frontend/source/js/data-capture/step_1.js
- frontend/source/js/data-capture/upload.js
> Fix #520 by manually constructing FormData

- frontend/source/js/tests/step_1_tests.js
I checked both natively and within our docker-compose setup.
@toolness: Please verify this works, and merge if so :)
> Fix for Blobs in Phantom 1.9.x and 2.1.x

- data_explorer/templates/index.html
- frontend/source/sass/data_explorer.scss
Related to trello card https://trello.com/c/3IO3aqAQ/121-visual-merge-issues
Closes #546, #547, and the remaining #521 education issue.
> Fix remaining visual merge bugs 

- frontend/source/js/data-capture/ajaxform.js
> Fix typo in ajaxform.js.

- .about.yml
- README.md
- compliance/component.yaml
Closes #610
Ref ATO issue: https://github.com/18F/Infrastructure/issues/649
Todo:
> remove references to QuantifiedCode

- data_capture/views/bulk_upload.py
- deploy.md
- manifests/manifest-sandbox.yml
- manifests/manifest-staging.yml
Open against `async-bulk-upload`.
> Add redis service instance to manifests

- styleguide/templates/styleguide.html
- styleguide/templates/styleguide_ajaxform_example.html
- styleguide/templatetags/styleguide.py
This is just #633 without the extra commit I added at the very end, right after @jseppi had reviewed everything.
Since @jseppi already approved this, I will insta-merge!
> Styleguide {% pathname %} and {% pyobjname %} tag improvements

- frontend/source/js/data-capture/ajaxform.js
- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/ajaxform_tests.js
This just adds some documentation for our web components. I don't want to cause doc rot down the road, so I've kept this fairly minimal for now, and only focus on what's most important and not totally obvious from reading the code.
> Document web components.

- data_capture/views/price_list_upload.py
Just some minor fixes for #583.
> get rid of some debugging code/comments

- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/upload_form.html
This adds some in-line TODOs for the form rejiggering, just to make sure they get addressed (we can create issues for them too, but I'd also like to memorialize them in the code if that's ok).
> Add todos to rejiggering forms PR

- CONTRIBUTING.md
Closes #695
also added a quick note about running `ultratest` with `docker-compose`
> doc how to run specific tests via ultratest

- .travis.yml
- Dockerfile
- package.json
> upgrade to node v6

- frontend/source/sass/base/_variables.scss
- frontend/source/sass/uswds/_utilities.scss
> Fix rem import issue

- data_capture/templates/data_capture/step.html
Closes #715 -- maybe this got lost in the Great Merge Conflict Resolution of #583.
> Add block tags for steps

- frontend/source/sass/components/_exceltables.scss
I figured we should explain ourselves here after #704!
> Explain use of font-family setting in excel table css.

- .travis.yml
- meta/management/commands/ultratest.py
- pytest.ini
reverts a43a49ac1807883560e4f5fe78923912a5e05519
closes #728
> change back to being explicit about adding the --cov flag

- data_capture/schedules/base.py
- data_capture/schedules/s70.py
- data_capture/templates/data_capture/price_list/upload_examples/schedule_70.html
- data_capture/tests/test_base_price_list.py
- data_capture/tests/test_s70.py
- data_capture/views/price_list_upload.py
~~**Note: This is a PR against #748, *not* `develop`.**~~
This fixes #727.
> <img width="733" alt="screen shot 2016-09-15 at 9 49 31 am" src="https://cloud.githubusercontent.com/assets/124687/18552297/c9910b62-7b29-11e6-9b3b-13141fc51736.png">
> Add schedule 70 upload example table

- README.md
- api/serializers.py
- api/tests/test_api.py
- api/views.py
- contracts/mommy_recipes.py
- data_capture/tests/test_index_view.py
- data_explorer/templates/about.html
- data_explorer/templates/index.html
- data_explorer/templatetags/schedules.py
> Micropurchase - Issue 612

- data_capture/forms/price_list.py
> Make contract start and end date fields required

- requirements.txt
security upgrade: https://www.djangoproject.com/weblog/2016/sep/26/security-releases/
> upgrade django to 1.8.15

- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/step_1.html
- data_capture/templates/data_capture/price_list/step_2.html
- frontend/templates/frontend/fieldset.html
- frontend/templatetags/frontend.py
**Note: This is a PR against #816, not `develop`.**
This fixes #808 by adding a `{% fieldset %}` tag, which basically functions like a macro.
> Add a {% fieldset %} template tag

- data_capture/forms/price_list.py
- data_capture/tests/test_forms.py
> validate contract_start is before contract_end

- data_explorer/templates/base.html
Fixes #887, #282.
Done as per the current snippet instructions in the [DAP readme](https://github.com/digital-analytics-program/gov-wide-code#participating-in-the-dap).
> Load DAP asynchronously

- manifests/manifest-staging.yml
This PR increases memory for `calc-dev` and `calc-rqworker` in `manifest-staging.yml`. The new values were figured out experimentally by going through the R10 Bulk Upload flow.
Closes #888
> increase memory on staging app and rqworker

- deploy.md
also remove outdated text about asking for a a CF account in #devops.
closes #877
> add note about cf-cli version

- README.md
> mention that using the load_data and load_s70 commands are optional

- frontend/source/js/data-capture/ajaxform.js
Er, I'm just making this change via github's web interface so hopefully this change will actually do what I think it should. 😁 
By which I mean, it should fix #1006.
> Fix #1006 (<select> and <textarea> in ajaxform).

- CHANGELOG.md
This attempts to update the "unreleased" section of the changelog to reflect what we've done over the past several months, since there hasn't really been a release since then.
It basically boils down to "we made data capture, and a bunch of minor improvements/bugfixes to data explorer".
> Update 'unreleased' section of changelog.

- CHANGELOG.md
@jseppi how's this for 2.1.0 release notes?
> Add release notes to changelog

- hourglass/changelog.py
- hourglass/tests/test_changelog.py
- meta/management/commands/bump_changelog.py
> Unwhackify github release heading

- frontend/source/js/data-explorer/autocomplete.js
> Set query when search field loses focus

- data_explorer/templates/_footer.html
- frontend/source/sass/components/_footer.scss
This will reduce text-wrapping frequency for larger viewports.
> Widens get in touch block and floats logos

- compliance/component.yaml
Work-in-progress during the ATO Sprint.
> Control narrative updates for 3-year ATO

- docs/docker.md
> Make cloud docker-compose.override.yml more DRY.

- frontend/source/js/common/hourglass.js
- frontend/source/js/data-explorer/autocomplete.js
- frontend/source/js/data-explorer/tests/__snapshots__/labor-category.test.jsx.snap
- frontend/source/js/data-explorer/tests/labor-category.test.jsx
- frontend/source/js/data-explorer/tests/util.test.js
- frontend/source/js/data-explorer/util.js
- frontend/source/js/tests/hourglass_tests.js
Open against #1376 
- move getLastCommaSeparatedTerm to utils
- add minimal tests for labor-category.jsx
> Minimal tests for <LaborCategory> component

- docker-update.sh
> Recommend `docker-compose down -v`

- docs/auth.md
- docs/environment.md
- docs/setup.md
- hourglass/tests/test_configuration.py
- requirements-dev.txt
This attempts to improve our `setup.md`, which is currently kind of vague and confusing.
[You can read the new version here.](https://github.com/18F/calc/blob/improve-setup-md/docs/setup.md)
This PR also renames a few sections to use [sentence case](https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98) because that's what the rest of our docs use and it's awesome.
To do:
> Improve setup.md

- data_capture/schedules/s70.py
- data_capture/schedules/spreadsheet_utils.py
- data_capture/tests/common.py
- data_capture/tests/test_s70.py
- data_capture/tests/test_spreadsheet_utils.py
> Backport refactorings from #1284

- styleguide/tests.py
Just realized that we didn't have tests for these, so I figured I'd add some.
> Add tests for styleguide email endpoints

- docs/api.md
- docs/frontend.md
- docs/index.rst
- docs/selenium.md
- docs/setup.md
- docs/testing.md
- styleguide/templates/styleguide.html
This is a first attempt at fixing #1360.
Thoughts @jseppi @hbillings ?
> Add a basic front-end guide

- data_capture/analysis/vocabulary.py
- data_capture/tests/test_analysis.py
> Ignore roman numerals in PL analysis

- data_capture/analysis/export.py
> Remove 'site' column from PL analysis export

- frontend/source/sass/admin/changelists.scss
- frontend/source/sass/admin/overrides.scss
- frontend/source/sass/components/_forms.scss
- hourglass/templates/admin/change_list.html
- hourglass/templates/admin/search_form.html
Closes #1326...
#1325 - This problem existed in the user/group search bar and dropdown group also, which now looks like this:
#1262 - looks like this now:
> Fixes to admin site

- data_explorer/templates/_banner.html
> Remove help-wanted link from site banner

- data_capture/schedules/coercers.py
- data_capture/schedules/spreadsheet_utils.py
> Call strip on text in extract_hour_unit_of_issue

- docs/setup.md
- hourglass/tests/test_configuration.py
> Mention postgres version in setup.md, test against it.

- docs/index.rst
- docs/monitoring.md
- hourglass/healthcheck.py
> Add docs/monitoring.md

- .travis.yml
- docker-compose.yml
- docs/setup.md
- hourglass/settings.py
> Upgrade to postgres 9.5.4

- contracts/loaders/region_10.py
- contracts/tests/test_region_10.py
> Region10Loader.make_contract() never returns None

- manifests/manifest-dev.yml
- manifests/manifest-prod.yml
- manifests/manifest-staging.yml
I *think* this might fix #1599.
> Remove DISABLE_COLLECTSTATIC for calc-rqworker

- .circleci/config.yml
- .codeclimate.yml
Updates our Code Climate config file format to the newest specification, as documented at https://docs.codeclimate.com/docs/advanced-configuration
closes #1625.
> Update Code Climate config

- requirements.txt
> Remove PyJWT

- docs/setup.md
> add note about `python` running Python 3

- data_capture/models.py
- docs/monitoring.md
- frontend/upload.py
Clears out a few old `TODO` comments from various places.
> Clear our some old TODO comments

- docs/environment.md
- frontend/gulp/webpack-util.js
> Add USE_POLLING env var

- frontend/source/js/data-explorer/tests/rates-request.test.js
- frontend/source/js/data-explorer/tests/serialization.test.js
> Add tests for Data Explorer serialization.js and rates-request.js

- docs/frontend.md
Minor updates to the QUnit docs in `frontend.md`.
> Fix some docs about qunit tests

- CONTRIBUTING.md
- docs/auth.md
- docs/docker.md
- docs/email.md
- docs/frontend.md
- docs/release.md
- docs/setup.md
- docs/testing.md
- hourglass/tests/test_configuration.py
Closes #1743.
This modifies all our developer documentation to assume that Docker/Docker Compose are used for running a CALC development environment.
> Default to dockerized project setup

- user_account/templates/account.html
> Remove empty card footer div on account page

- frontend/source/sass/base/_variables.scss
- frontend/source/sass/components/_footer.scss
Had to wait for `er-palette-a-go-go` to merge before these variables could be applied.
> Updates a green variable name and applies color variables to footer

- data_explorer/templates/analytics/dap.html
- data_explorer/templates/analytics/ga.html
- data_explorer/templates/base.html
- docs/analytics.md
- docs/deploy.md
- docs/index.rst
Fixes #847.  Thanks to #1852 and #1853, this is pretty straightforward!
> Add docs for analytics

- frontend/source/sass/base/_variables.scss
- frontend/source/sass/components/_page.scss
- frontend/source/sass/data_explorer.scss
Also added a touch more saturation to `$color-gray-lightest`
> Darkens site bg to match design

- .about.yml
- README.md
> Remove references to Trello, link to /docs/ on dev server from README

- frontend/source/sass/base/_typography.scss
- frontend/source/sass/base/_variables.scss
> Consolidate indentation rules

- frontend/source/js/data-explorer/components/export-data.jsx
- frontend/source/js/data-explorer/tests/__snapshots__/export-data.test.jsx.snap
- frontend/source/sass/components/_buttons.scss
> Fixes for buttons

- frontend/templates/frontend/fieldset.html
- frontend/templates/frontend/steps.html
Closes #1957. Turns out I missed just a couple of them somehow when I did this originally.
> Apply usa-sr-classes everywhere

- contracts/reports/dupes.py
> Document _get_dupe_info()

- frontend/source/sass/admin/overrides.scss
> Fix sliver of space under admin padding

- data_capture/templates/data_capture/price_list/step_4.html
Button at the bottom of data-upload step 4 wasn't referencing the style correctly in the html.
> Fix for step 4 previous btn

- frontend/source/sass/admin/overrides.scss
- frontend/source/sass/components/_tables.scss
Closes #1970. Looks like this now:
> Fix admin data table wonkiness

- data_explorer/templates/_header.html
- data_explorer/templates/_nav.html
um yes I typoed the issue number in my branch name 😬 
Pulls in just the UI updates from #2102.
> Patch for `2102-relocate-admin-link`

- frontend/source/sass/data_explorer.scss
Fixes results-table problem where rows with only one line of data (not counting contract link) change their height on hover.
> Combine 2 cols hotfix

- .circleci/config.yml
- data_capture/tests/test_analysis.py
- frontend/source/js/data-explorer/components/schedule.jsx
- frontend/source/js/data-explorer/tests/__snapshots__/business-size.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/loadable-wrapper.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/schedule.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/site.test.jsx.snap
- package.json
- yarn.lock
Attempt to fix #2124. This will need to be folded into `develop` if it works, also.
https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile
> Change CircleCI config and update Jest

- frontend/source/js/data-explorer/components/schedule.jsx
- frontend/source/js/data-explorer/components/search-category.jsx
- frontend/source/js/data-explorer/tests/__snapshots__/schedule.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/search-category.test.jsx.snap
- frontend/source/sass/components/_forms.scss
Adjusted styles, edited some labels, and rearranged the list order to accommodate our ever-growing list of contract vehicles. Now when more get added, the vendor / contract search won't get buried at the bottom.
> Vendor contract ui changes er

- data_explorer/templates/_nav.html
This tutorial
Was not supposed to be here
Thus we remove it.
> Remove add price data tutorial link.

- .circleci/config.yml
- .gitattributes
- cf.sh
- data_capture/analysis/vocabulary.py
- docker-compose.yml
- docker-services.yml
- update.sh
Why reach for the clouds
When what we need for language
Could be right here now.
Add NLTK's Averaged Perceptron Tagger .pickle file to repository instead of downloading it on every build, and make changes to build files and to price analysis reflecting those changes.
> Add NLTK's Averaged Perceptron Tagger .pickle file

- data_capture/analysis/vocabulary.py
Valid inquiry
Does not always have a place
In production code.
> Remove stray debug lines.

- .circleci/config.yml
- .gitattributes
- CHANGELOG.md
- cf.sh
- data_capture/analysis/vocabulary.py
- docker-compose.yml
- docker-services.yml
- update.sh
- Add NLTK's Averaged Perceptron Tagger `.pickle` file to repository instead of
downloading it on every build, and make changes to build files and to price
analysis reflecting those changes. (#2194)
> Tag and release v3.2.2 to production

- data_explorer/templates/_footer.html
This reverts commit 7273c25eb2d02fc4380a057f8252e877a9a050bd.
> Revert "Dev Deployment"

- CHANGELOG.md
This reverts commit 796e5ff2c584a7d2c59861fe11f1fa2155ed023b.
> Revert "Removed Some Entries from change logs"

- api/capability_statement/capability_statement.py
PSHCDT-56  CALC's About Page 
PSHCDT-161 Refinement of disclaimer under the search box.
> PROD Deplooyment

- requirements.txt
Django version upgrade to 1.11.27 or greater
> Snyk fixes 2 6

- requirements.txt
> security fixes

- calc/settings.py
> Theodesta uaa logout patch 1

- data_capture/templates/data_capture/analyze_price_list/step_3.html
Width fix for the price list is modified.
> Width fix for price list

- calc/settings.py
- data_capture/analysis/core.py
- data_capture/templates/admin/data_capture/view_attempted_submission.html
- data_capture/templates/data_capture/analyze_price_list/step_1.html
- data_capture/templates/data_capture/analyze_price_list/step_2.html
- data_capture/templates/data_capture/analyze_price_list/step_2_errors.html
- data_capture/templates/data_capture/analyze_price_list/upload_form.html
- data_capture/templates/data_capture/price_list/step_1.html
- data_capture/templates/data_capture/price_list/step_3.html
- data_capture/templates/data_capture/price_list/step_3_errors.html
- data_capture/templates/data_capture/price_list/step_4.html
- data_capture/templates/data_capture/price_list/upload_form.html
- data_capture/templates/data_capture/step.html
- data_capture/templates/price_lists/details.html
- data_capture/views/bulk_upload.py
- data_capture/views/price_lists.py
> Revert "Brmp 1722 load test csrf"
