GSA/calc

- api/serializers.py
- api/tests.py
- api/views.py
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/templates/index.html
- requirements.txt
Introducing the wage histogram!
This comes courtesy of a new `/api/rates/` query parameter, `?histogram=x`. When specified, a `wage_histogram` array of `x` length is added onto the results object, and it looks like this:
```js
"wage_histogram": [
{
"count": 42, 
"max": 53.408000000000001, 
"min": 20.809999999999999
}, 
// ...
{
"count": 1, 
"max": 346.79000000000002, 
"min": 314.19200000000001
}
]
```
This needs to be tested. I've got a simple doctest in [api.views#get_histogram()](https://github.com/shawnbot/hourglass/commit/11167009e985f9cf323f0916df40869e25d2376c#diff-265524153427c5c3f0dd9ae087f16a4bR68), and the visual output looks right, but there are some edge cases to watch out for. In order for the visual histogram to be accurate, we should assert that:
1. `wage_histogram[0].min …
> Add wage histogram

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/templates/index.html
- selenium_tests/tests.py
Introducing collapsible table columns. Activating these is as simple as adding the `collapsible` class to any of the `#results-table th` elements in the index template. I've done so with the [schedule column](https://trello.com/c/GwHnSAu5/40-show-or-make-available-schedule-name-in-results), and have tested it with other columns as well. Collapsing a column hides both the `th` element's text *and* the corresponding `td` elements' text. This was necessary because laying out HTML tables is tricky when there's text in all of the columns, and there wasn't an easy way to "collapse" the cells containing lots of text in CSS alone. A collapsed column looks like this (on the far right):
There's a `title` attribute on the ◀ icon that reads "Show Schedule" and switches to "Hide Schedule" when you …
> Collapsible table columns

- .gitignore
- selenium_tests/tests.py
- No longer hardcoding the dev server, using live_server_url instead
- Generate test data
- Rewrite some tests to take advantage of known test data
- Should be invoked with something like:
./manage.py test --liveserver=localhost:8081-8181
- Eliminate asserts that are redundant w/ API tests
- Set longMessage so that built-in failure messages show alongside
custom ones
> Selenium test improvements

- hourglass_site/static/hourglass_site/style/main.css
The Schedule column is now sortable and collapsible, resolving #44:
@brethauer, should I ditch the little left/right triangle in the "show/shide" text and nudge it left by a couple of px, per your sketch?
Also seems like it needs some `text-decoration: underline` and a lighter color, huh?
> Allow columns to be sortable and collapsible

- hourglass_site/static/hourglass_site/js/index.js
- selenium_tests/tests.py
This PR tweaks the histogram appearance and adds the following tests in #43, which now pass:
* visual way of showing price distribution is shown for results that are displayed
* Min/max/average is displayed
I've also adjusted the test for the price inputs showing up last to ignore the hidden input, as that may change. `testResultsCount()` does some sanity checking (and stripping of commas) before trying to coerce the result count as an integer.
> Histogram selenium tests

- hourglass_site/static/hourglass_site/style/main.css
When you sort by Schedule ascending, you can see that the last cell of each row in the results table has no right padding. This fixes that.
> Fix padding-right in table cells

- Makefile
- hourglass_site/static/hourglass_site/js/index.js
- selenium_tests/tests.py
This PR wraps up the histogram selenium tests in #43, and introduces some nicer title text on the histogram bars:
The selenium test for the tooltips just ensures that there is a `<title>` element inside each of the `.histogram .bar` elements, which is SVG-specific but can be easily changed to test for a `title` attribute if we ever switch to HTML.
> More tests

- api/tests.py
- contracts/models.py
- Refactored all order_by()s into a single extra(), since Django deliberately
discards all but the last order_by
- Tests now allow checking just a subset of expected keys against results-- more concise tests!
> Preserved order_by precedence when there are multiple params

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/index.html
This is a fix for #82 that also renames the submit and reset buttons so that we don't override the form DOM object's `submit()` and `reset()` methods.
> Query type tweaks

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/templates/index.html
This updates the text above the results table to dynamically list all of the active filters, per [this card](https://trello.com/c/do7QFAAg/29-help-users-understand-state-of-their-search-and-the-data-in-results-what-is-loaded-based-on-their-search-filters). Here's how it works:
* When there are no active filters (or search terms), it simply reads, `Showing 200 of 49,528 results`
* When you search for a labor category, it changes to `Showing 121 of 121 results matching “labor category”`
Any additional filters will tack on bits that read something like `, and [field] {value}`, with slight variations for each filter. These are defined as string templates [here](https://github.com/18F/calc/blob/query-description/hourglass_site/static/hourglass_site/js/index.js#L568-L574), in which the …
> Add query description

- hourglass_site/static/hourglass_site/js/index.js
The problem was a regression in my fix to #77, where I added a step in the linear scale for 1, which made the domain of the y-axis scale `[0, 1, max]`. It does the right thing now:
> Fix y-axis labels in #94

- hourglass/local_settings.example.py
- hourglass/settings.py
- hourglass_site/static/hourglass_site/js/hourglass.js
- hourglass_site/static/hourglass_site/tests/qunit-1.16.0.css
- hourglass_site/static/hourglass_site/tests/qunit-1.16.0.js
- hourglass_site/templates/base.html
- hourglass_site/templates/tests.html
This PR updates `settings.py` with a reasonable default for `API_HOST` that works on localhost without having to set environment variables or modify `local_settings.py`. (While I was in there I also added the `REMOTE_TESTING` defaults so this will not fail on CI.)
The `API_HOST` is now assumed to have a slash at the end, but the JS will add it if there isn't one. Rather than applying a very naïve regex, the JS API now also strips the preceding slash from any URI before prefixing it with the base path.
The API unit tests now pass, which means that this *should* work in production. :grimacing:
> Fix API host weirdness

- hourglass_site/static/hourglass_site/js/index.js
The histogram x-axis labels are now all rounded to remove the cent values:
> Fix #95: truncate price values on histogram x-axis

- api/permissions.py
- hourglass_site/static/hourglass_site/js/index.js
- selenium_tests/tests.py
This PR includes a fix for #117 and some miscellaneous fixes for the Selenium tests. @kaitlin I could use your eye on the `api/permissions.py` change, specifically. The deal there was that when running the Selenium tests on Sauce through https://localtunnel.me, the `X-Forwarded-For` header is set to a raw IP address, so the line that parses out the comma-separated bits was failing.
> Clear excluded rows on form reset

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/base.html
This is a slight rewrite of #126 that adds IE-specific classes to the `<body>` and addresses the label positioning with a qualified CSS selector: `.ie etc.`.
> Fix IE labels

- .travis.yml
- Makefile
- README.md
- hourglass/local_settings.travis.py
- hourglass/setup.sql
This fixes #76 by adding a `.travis.yml` file that runs the tests in both Python 2.7 and 3.4 (which will be handy for detecting changes that break 2.x installs).
> Add Travis continuous integration

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/index.html
Adds `title` attributes to all sortable headers that reflect their current state, for instance when a column is sorted it gets the title, "{title}: sorted {order}, click to sort {opposite order}".
@bristow, we decided to use `title` instead of sr-only spans and replaced one instance of `aria-describedby` that looked wrong. Thanks for taking a look!
Also, we killed the sortable class toggles on un-sortable columns.
> Fix 508 sort headers

- hourglass_site/static/hourglass_site/js/index.js
This updates the x-axis label on the histogram from price to "price (hourly rate)"
It is currently lowercase italics, but happy to change to uppercase if people prefer.
> Update price label on x-axis

- README.md
- api/tests.py
- api/views.py
- hourglass_site/templates/index.html
Instead of the user filtering on a minimum level of experience, the user can now choose a range of experience, in increments of five years. 
This also adds the `experience_range` API filter, which takes a range of years and delegates to `min_experience` and `max_experience`.
> Adding experience range dropdown filter and corresponding API functionality

- hourglass_site/static/hourglass_site/js/index.js
This updates the dynamic sentence (mad-libs style) created above the histogram when selecting filters. I've removed the min/max price and changed min experience to experience range.
This is what it looks like now:
> Update dynamic sentence

- hourglass_site/templates/index.html
I added back in sortability for the Vendor column. This is what it looks like:
> Add vendor sortability back

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/static/hourglass_site/style/tables.css
While I do love our bright and fresh blue, @brethauer noted they didn't pass color contrast checks for 508 accessibility here: https://github.com/18F/calc/issues/152
Here's how it looks with accessible colors:
> Fix color contrast for 508 accessibility

- hourglass_site/templates/index.html
We had an unclosed div of a row that I closed. FF does not close unclosed divs which is why we had an issue only in FF before. This resolves: https://github.com/18F/calc/issues/149
> Fix loading indicator layout

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
This will preserve the mobile layout and allow people to scroll horizontally to view the table. Before the whole page shifted.
This implements this fix found here: https://github.com/18F/calc/issues/158 thanks to @blacktm
This is how it looks now:
> Fix table for responsive

- hourglass_site/static/hourglass_site/images/document.svg
- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- selenium_tests/tests.py
Adds a link to each contract ID that goes to the contract in the form a PDF or other document type hosted on the GSA eLibrary.
Notes:
- If more markup ends up in the JS, we should probably come up with a cleaner plan.
- I tried to add a test to make sure that the document we link to in our test case still exists, but the redirect on the GSA side didn't appear to be working. Its kind of testing someone else's functionality, so maybe that's for the best, but inevitably these urls will change and it'd be nice to find out from a test.
> Link contracts from GSA eLibrary in table

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/js/vendor/jquery.tooltipster.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/tooltipster.css
- hourglass_site/templates/base.html
- hourglass_site/templates/index.html
- selenium_tests/tests.py
WIP :warning: :construction: 
This uses [tooltipster.js](http://iamceege.github.io/tooltipster/) to display tooltips on table headers and exclude rows. This displays the dynamic content on `aria-label` (was previously `title`) for greater accessibility.
Thanks to @theresaanna and @shawnbot!
Table headers:
Exclude results:
There is a bug where bc the “Hide Schedule” button is structured inside a table header, the tooltip is firing on hover, even though it is visually outside of it. One idea is to move the hide button outside of the table header.
> Add tooltips and use aria-label

- hourglass_site/static/hourglass_site/style/tables.css
Looks like the sort arrows are reserved. This sets them so that pointing down is descending and pointing up is ascending.
**Old**
**New**
> Reverse sort arrows

- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/templates/base.html
- hourglass_site/templates/index.html
This adds "ceiling" before "price" in the text in the **main header**, **histogram x-axis**, and **results table**. This accomplishes the first two tasks in trello: https://trello.com/c/pHF7rMN0/134-further-clarify-that-the-prices-in-calc-are-ceiling-level-prof-services-schedule-only-worldwide
**main header**:
**histogram x-axis**:
**results table**:
Note: we'll need to resize columns so that we can fit "ceiling price" on a single line. Otherwise it jumps to two lines.
> Clarify price

- cf.sh
- manifest.yml
- requirements.txt
Also locks us to a known working version of pgfulltext as there are issues with the newest version. First, the issue described here: https://github.com/linuxlewis/djorm-ext-pgfulltext/pull/59 and, per Ozzy, it sounds like theres some encoding change between 0.9.3 and 0.9.4 that he ran into while helping me with the migration + Cloud Foundry work.
> Run Django migrations and load_data script when pushing to Cloud Foundry

- api/serializers.py
- api/tests.py
- api/views.py
- hourglass_site/static/hourglass_site/js/index.js
- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
This adds a standard deviation callout below the graph. It also moves the two download buttons together below the callout. This does work around: https://github.com/18F/calc/issues/176.
Here is what it looks like:
Great work on the functionality by @theresaanna!
> [WIP] Add standard deviation callout

- hourglass_site/templates/base.html
This adds attribution for the icons used in the header area. Attribution is added in the footer.
> Add icon attribution

- selenium_tests/tests.py
It seems as though this changeset prevents the test timeouts we've been seeing, but the broken pipe errors may need to wait a bit longer.
> Fixing Selenium tests

- manifest.yml
- runtime.txt
The buildpack has changed and the Python version we use in CF needs to change along with it.
> Updating Cloud Foundry buildpack

- api/tests.py
- api/views.py
This morning, in production, we had an issue where requests were timing out. After consulting New Relic, it looks like the app errored when a user submitted a couple search terms that included parentheses. 
This pull requests makes it so that, when users search using the default setting, "Contains words", non-query-friendly characters are stripped out of the query, leaving just alphanumeric characters and whitespaces.
> Strip non-alpha numeric or whitespace chars out of search query

- api/tests.py
- api/views.py
Looking at the errors users encountered that have been logged in New Relic, I noticed that they all had double spaces in the search term, which caused `convert_to_tsquery` to format queries like `senior & & engineer:*`, which causes errors as it is invalid syntax.
I rewrote `convert_to_tsquery` to address this. I also added prefix matching to each chunk of the query. So, for example, if someone searches "staffing consultant" with default search settings, they now get results for categories like "staff consultant". Previously, only the last term would have prefix matching applied.
> Rework the method by which raw queries are formatted

- hourglass_site/static/hourglass_site/js/index.js
- Removes tspans for both the average and proposed price labels. This makes the average price label show up. For some reason, canvg has problems with tspans. 
- Adjusted the dimensions of the generated canvas so that the final image will be the correct size. This fixes the stretching.
> Fixes stretching and missing label in downloadable graph

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/static/hourglass_site/style/main.css
- hourglass_site/static/hourglass_site/style/tables.css
- hourglass_site/templates/index.html
This updates placeholder text and other additional text to a darker gray. This also lightens some gray text used as labels for the histogram and table headers. This follows WCAG AA guidelines.
> Update to accessible grays

- hourglass_site/static/hourglass_site/style/index.css
- hourglass_site/templates/index.html
This adds help text around the search field which lets users know they can enter multiple terms and how to do it: 
Use a comma between words to search multiple terms. (For example: Engineer, Consultant)
This addresses:
https://trello.com/c/en3kpl5i/170-make-it-obvious-that-user-can-search-multiple-terms
> [WIP] Add search help text

- hourglass_site/static/hourglass_site/style/index.css
This adds a fix for the focus state so the text doesn't shift when you trigger the focus state. It also makes the focus state consistent across all inputs.
> Fix focus state

- hourglass_site/templates/base.html
This changes our DAP embed code to:
```
<script id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA"></script>
```
This takes advantage of the DAP's new [centrally hosted JavaScript code](https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/), which means 18f.gsa.gov will automatically get security updates, new features, and other bugfixes automatically.
This PR also tightens up the GA settings to match [18F's standard settings](https://github.com/18F/analytics-standards#18f-snippet-standards-for-website-analytics).
> Updates DAP location, tightens GA settings

- requirements.txt
This fixes #279.
However, as mentioned in that issue, there are some `RemovedInDjango19Warning` messages that are logged, which unfortunately aren't very easy to fix because they come from third-party libraries that are either not well-maintained, or whose upgrade paths involve non-trivial changes to our code:
* Our version 3.0.5 of `rest_framework` is using `django.utils.importlib`, which is removed in 1.9. Unfortunately, upgrading it requires dealing with the fact that [`PaginationSerializer` was deprecated in 3.1](http://stackoverflow.com/questions/31500192/django-rest-framework-error-cannot-import-name-paginationserializer/31500287#31500287), which will require refactoring our code.
* During `manage.py load_data`, our version of `djorm_pgfulltext` is using `django.db.models.get_app` …
> Upgrade to Django 1.8

- hourglass_site/static/hourglass_site/js/index.js
This fixes #244 and #289.
I'm not really sure what I'm doing here, though, as I'm totally unfamiliar with the front-end code. I basically just added the minimum amount of code to ensure that the browser doesn't throw an exception or log any SVG attribute errors.
From an end-user perspective, though, this solution seems nice because one can now enter queries that return no results, and the graph is updated (it previously would remain unchanged due to the JS exception being thrown).  That said, the graph isn't updated to anything *particularly* user-friendly:
But hey, it's still better than the graph not updating *at all*, right? :grin:
> Fix empty price histogram

- api/pagination.py
- api/serializers.py
- api/tests.py
- api/views.py
- requirements.txt
This fixes #290 by upgrading us to Django REST Framework 3.1.
Note that the latest version of DRF is 3.3, and I doubt we should run into any major barriers upgrading it all the way there, but I'd rather save it for a separate PR.
As mentioned in #290, upgrading to DRF 3.1 was non-trivial because of its architectural overhaul of pagination.
I believe this PR has feature parity with the existing API, with the following changes:
* On the existing API, submitting an API request for a non-integer page, e.g. `page=blarg`, results in a 500 internal server error.  This PR fixes the bug by delegating all pagination to DRF's `PageNumberPagination`, which returns the following response:
```http
HTTP 404 Not Found
Vary: Accept
Content-Type: application/json
Allow: GET, HEAD, OPTIONS
{
"detail": …
```
> Upgrade to Django REST Framework 3.1

- api/tests.py
- api/views.py
This fixes #250.
Note that it ~~preserves~~ changes the current behavior of the API, which *seems* to be non-standard, as `first_standard_deviation` is set to `NaN` when there are empty results--yet [the JSON specification claims `NaN` should be specified as `null`](http://stackoverflow.com/q/1423081).
But indeed, querying an empty result set from the API yields a `"first_standard_deviation": NaN`, and piping the response through `python -m json.tool` works fine, which makes me wonder if maybe it was added to the standard at some point... yet in JS, `JSON.parse('{"boop": NaN}')` raises a syntax error, so perhaps we're actually outputting illegal JSON in our API!
> Fix numpy warning.

- README.md
- docker-compose.yml
- hourglass/local_settings.example.py
- hourglass/settings.py
This fixes #280.
Note that in production, this will require configuring the cloud.gov environment to set a `SECRET_KEY` environment variable. According to the [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#env-block) I think this can probably be done with something like:
```
cf set-env SECRET_KEY boop
```
However, depending on how we deploy the app, we might need to somehow ensure that this environment variable is still defined whenever we re-deploy... This could potentially get complicated with a zero-downtime tool like [autopilot](https://github.com/concourse/autopilot), I'm not sure though.
> Take SECRET_KEY from environment.

- .gitignore
- README.md
- deploy.md
- hourglass/settings.py
- hourglass/settings_utils.py
- hourglass/tests.py
- requirements.txt
This fixes #306.
The `load_cups_from_vcap_services()` function was largely inspired by [python-dotenv](https://github.com/theskumar/python-dotenv#readme).
The documentation is largely cribbed from [team-api-server](https://github.com/18F/team-api-server/blob/master/README.md#on-cloudgov)'s.
> Add support for cloudfoundry CUPS.

- README.md
It seems as though https://travis-ci.org/18F/calc.svg just shows the build status of the most recent build, even if it's e.g. a WIP PR that's currently broken.  If we explicitly add `?branch=develop` to the URL then we'll get the status of the current `develop` branch.
> Use branch=develop for travis CI badge

- README.md
This removes references to docker-machine, since Docker has gone native for OS X / Windows (although it is still in beta).  It also links to the 18F docker guide and documents updating the container.
> Updated docker docs in README.

- hourglass/settings.py
This fixes #213.
I've had an extremely frustrating time using whitenoise in development due to errors like #213 that intermittently come up during development and [testing](https://travis-ci.org/18F/calc/builds/140849798).
The only way I can think of to remedy this is by disabling whitenoise's `CompressedManifestStaticFilesStorage` entirely during development. It's not great for dev/prod parity but I also can't really imagine it having negative effects, unless we forget to use the `static` template tag and hardcode a URL to a static asset, but we should be able to easily catch that during code review.
I originally tried to remove our `collectstatic` call before running selenium tests, but they bizarrely fail without them, which I suppose is par for the course when it comes to selenium at …
> Only use whitenoise CompressedManifestStaticFilesStorage in production.

- .coveragerc
- .travis.yml
- README.md
- requirements.txt
This PR modifies the Travis build to report coverage information to CodeClimate.
One step not shown here in code is that I had to set the `CODECLIMATE_REPO_TOKEN` in Travis (as a private env variable).
> add code coverage reporting via code climate

- .about.yml
Updated the `.about.yml` project metadata for CALC. This is a required part of the ATO process, ref https://github.com/18F/Infrastructure/issues/649.
Should merge #350 before this PR since the modification here makes reference to the QuantifiedCode integration and badge.
Closes #349
> update .about.yml to include data capture project details

- .travis.yml
Remove the explicit disabling of email notifications, which should revert travis back to its default email notification behavior of emailing the committer who broke the build.
> reenable default travis email notifications

- qunit_tests/tests.py
- qunit_tests/vendor/LICENSE
- qunit_tests/vendor/README.md
- qunit_tests/vendor/runner.js
- selenium_tests/tests.py
- selenium_tests/utils.py
This should have been really easy but it took me a while because `whitenoise` is confusing.
I copied `runner.js` from [qunit-phantomjs-runner](https://github.com/jonkemp/qunit-phantomjs-runner) because:
1. Finding the file when it's installed via `npm` is actually non-trivial due to #373.
2. It's just one dinky file that doesn't change often.
If we really want, though, I can install it via `npm` and add code to locate the `node_modules` directory it's located in.
> Run QUnit tests in phantomjs

- hourglass_site/static_source/style/main.scss
- hourglass_site/static_source/style/widgets/_steps.scss
- styleguide/templates/styleguide.html
**Note:** This PR supersedes #380, which was based against the `styleguide` branch. This is the same code based against the `develop` branch, since the styleguide was merged in #378.
This adds a steps widget to the styleguide:
> <img width="733" alt="screen shot 2016-07-13 at 10 00 29 am" src="https://cloud.githubusercontent.com/assets/124687/16806214/996776ee-48e1-11e6-8e31-cae53e4f50d3.png">
We should be fine to use SVGs in general, as the only browser that doesn't support them is IE8, and Kelly confirmed that we don't need to be concerned with that browser.
However, I am not a huge fan of how verbose the `<svg>`s are in particular.  Alternatives:
* Use pure CSS, although that could get kind of gnarly, especially when it comes to the stroked circles in the unfinished steps.
* Create …
> Add steps widget to styleguide (take 2)

- deploy.md
- manifests/manifest-staging.yml
- newrelic.ini
- Documented New Relic stuff in `deploy.md`.
- Updated `manifest-staging.yml` to include non-secret New Relic env vars
- Manually deployed to cloud.gov and verified that "CALC (staging)" is showing up in our New Relic console.
> New Relic documentation and config

- gulpfile.js
- hourglass_site/static/hourglass_site/js/upload_tests.js
- hourglass_site/static_source/js/common/upload.js
- hourglass_site/static_source/style/main.scss
- hourglass_site/static_source/style/widgets/_upload.scss
- hourglass_site/templates/base.html
- hourglass_site/templates/tests.html
- styleguide/templates/styleguide.html
**[The current work-in-progress can temporarily be viewed here.](http://54.87.247.188/styleguide/#upload)**
* One frustrating thing about using HTML5 Drag-and-Drop is that once you opt-in to it, you also have to do any file uploads via Ajax, because `<input type="file">` is read-only.  So we'll have to support that out-of-the-box too.
* This widget provides visual feedback when the user is dragging a file over it, it's just currently very subtle (switches background from off-white to white).  We can make it more obvious easily, though.
* The widget works without degradation in IE11 and the latest versions of Chrome, Firefox, Edge, and Safari.
* The widget reads fine on NVDA and VoiceOver. We dynamically add `aria-live="polite"` to the upload widget so that its changes are narrated to the …
> Add upload widget

- styleguide/static/styleguide/styleguide.css
- styleguide/templates/styleguide.html
- styleguide/templates/styleguide_section.html
- styleguide/templates/styleguide_with_toc.html
- styleguide/templatetags/styleguide.py
This gives us a handy table of contents to the style guide, and interactive anchors next to sections that we can use to generate hyperlinks:
> ![toc](https://cloud.githubusercontent.com/assets/124687/16874605/4f7d8e5a-4a68-11e6-969b-0d27163cd3cf.png)
In the above screenshot, the `#` in the margin (across from the "Upload Widget" heading) is being displayed because my cursor is over it; otherwise it doesn't appear. This is based on the interaction model of GitHub READMEs.
It's pretty barebones right now; we can't have subsections (so the subsections of the Upload Widget section are just static headings) and the TOC doesn't stay with you as you scroll along the page or anything, but it's a start! We can upgrade it later as our style guide becomes more complex.
> Add table of contents to style guide

- docker-compose.local.yml
This fixes #401.
Now only one annoyance remains when using nodeJS in Docker, which is that [ESLint doesn't respect `NODE_PATH`](https://github.com/benmosher/eslint-plugin-import/issues/142), so it will think that all our `require()` statements are bogus, but whatever.
> Ignore 'node_modules' in docker volume mount.

- hourglass_site/static/hourglass_site/js/upload_tests.js
- hourglass_site/static_source/js/data-capture/upload.js
- styleguide/templates/styleguide.html
Adds validation to the upload widget via the `accept` attribute on the file `<input>`.  Note that this behavior is not fool-proof, so server-side validation will obviously still need to be done. However, it should be slightly nicer user-wise because 1) their OS file chooser will only show accepted file types (unless they manually override it) and 2) non-accepted files will not populate the widget when dropped.
Another thing I had wanted to do was add a class when a non-accepted file type was dragged over but not yet dropped. Unfortunately the list of file objects doesn't seem to get populated in the drag event, only in the drop event, so that is not possible.
TODO:
Here is what it looks like when an invalid file type is dropped or selected:
Closes https://github.com/18F/calc/issues/394
> Validate upload file type

- .eslintrc
- meta/management/commands/ultratest.py
This is a workaround for https://github.com/benmosher/eslint-plugin-import/issues/142. I figure it's OK to ignore this warning since there's a very high likelihood that our code simply won't run / compile if there are any unresolved imports.
> Ignore unresolved imports from eslint for Docker support.

- gulpfile.js
Previously, I wasn't including enough of the steps of the SASS->CSS pipeline within the `gulp-sourcemap` transforms. Now when an element is inspected with developer tools, you will be able to see in which `.scss` file a rule is defined.
> fix generation of style sourcemaps so they include the sass sources

- gulpfile.js
Closes #437
Basically, gulp and watchify were both watching the data-capture javascript files, so each time a file was changed, the browserify bundling stuff was getting added again, resulting in all kinds of funkiness.
Please excuse the typo'd branch name >.<
> fix multiple rebundles

- package.json
Use `--max-warnings 0` arg so `npm run failable-eslint` fails on warnings
> eslint fail on warnings for ultratest

- .bandit
- .travis.yml
- README.md
- meta/management/commands/ultratest.py
- requirements.txt
This adds `bandit` to both ultratest and to our CI tests. 
Ready for review, @toolness 
Related: https://github.com/18F/calc/pull/405 and https://github.com/18F/Infrastructure/issues/649 (our ATO issue)
> add bandit scanning to ultratest and travis

- compliance/component.yaml
- opencontrol.yaml
This is just an initial attempt at doing something with compliance masonry.
This is based off the files in `epa-notice`:
* [`compliance/component.yaml`](https://github.com/18F/epa-notice/blob/master/compliance/component.yaml)
* [`opencontrol.yaml`](https://github.com/18F/epa-notice/blob/master/opencontrol.yaml)
> Add compliance masonry YAML files

- .about.yml
- README.md
Related: https://github.com/18F/calc/pull/405
I don't know how often gemnasium updates, but right now it says our Django version needs to be updated from 1.8.13 to 1.8.14, but we have already made that upgrade in https://github.com/18F/calc/blob/develop/requirements.txt#L3
> add gemnasium badge to readme

- data_capture/templates/data_capture/step.html
- data_capture/templates/data_capture/step_2.html
Part of #454 - This removes the inline styles and matches the styleguide markup for the price list errors found during upload. It also brings in `data_capture.min.css` to the `step.html` template.
It still shows the red box'd errors in the table cells with errors. @hbillings: how should we display these error messages, via a tooltip perhaps?
> Price list alert markup and styling

- api/tests/test_doctests.py
- api/views.py
- hourglass_site/static/hourglass_site/js/hourglass_tests.js
- hourglass_site/static_source/js/common/hourglass.js
- hourglass_site/static_source/js/data-explorer/index.js
This fixes #458.
At first I thought that the problem was in `convert_to_tsquery()`, so I started by writing a doctest for it, but it turned out to work fine.  I left the doctest in, though, since I think it helps improve readability of the code.
> Fix multi-word autocomplete

- data_capture/templates/data_capture/step.html
- hourglass_site/static_source/style/components/_header.scss
- hourglass_site/templates/base.html
This fixes #383 by enclosing the non-slim part of the header in a `header_extension` block, which allows child templates to redefine it as empty (or, alternatively, add their own custom extension content). It also shuffles around some CSS so that there's a decent bottom margin on the slim version of the header.
Here is the normal header:
> ![fattington-header](https://cloud.githubusercontent.com/assets/124687/17247243/e50e8102-555f-11e6-94fc-a69f32086354.png)
And here's the slim one:
> ![slim-header](https://cloud.githubusercontent.com/assets/124687/17247245/e8cd6826-555f-11e6-9eb4-8325599f4dbf.png)
In the future we can potentially reverse things so that the header is actually slim by default, and the index and about pages are the only ones that include the big version, but I wanted to …
> Use slim header for data capture.

- data_capture/schedules/s70.py
As discussed in https://github.com/18F/calc/pull/473#issuecomment-236175343, it'd be nice to check `price_including_iff` (another required field) to determine whether we've reached the end of the price list.
> Also check price_including_iff to determine when s70 price lists end.

- hourglass/middleware.py
- hourglass/settings.py
- hourglass/urls.py
- requirements.txt
This gives us the fancy [Django Debug Toolbar](https://django-debug-toolbar.readthedocs.io/en/stable/index.html) when `DEBUG` is `True`.
> ![screen shot 2016-07-29 at 2 12 17 pm](https://cloud.githubusercontent.com/assets/124687/17258773/8113b366-5596-11e6-9540-8c6d5d5dac30.png)
The one major item of note here is that we *always* show the toolbar when `DEBUG` is `True`, rather than relying on the toolbar's default configuration of consulting `INTERNAL_IPS`, which makes using the toolbar under Docker and e.g. on a tablet over one's local wifi particularly cumbersome.
If this seems too insecure even for debug mode, I can modify the behavior so that it only displays the toolbar if it's running in Docker *or* the client is listed in `INTERNAL_IPS`. This would still make it hard to use the …
> Add support for django debug toolbar

- .codeclimate.yml
We aren't writing CSS any more, just SCSS, so CodeClimate's csslint just produces noise on vendor files mostly.
> remove csslint from codeclimate

- hourglass_site/static_source/js/data-capture/index.js
- hourglass_site/static_source/js/data-capture/tablesort.js
- hourglass_site/static_source/style/components/_alerts.scss
- styleguide/static/styleguide/styleguide.css
- styleguide/templates/styleguide.html
I went ahead and made some minor changes to @hbillings original PR #452.
- Fix typo'd `@import`
- Adjust styleguide css to better align h3 headings with their border-bottom
- Extract tablesorting script from styleguide.html to its own file as part of data-capture js bundle. Also ES6ify it and bring it up to our eslint standard. No logic or other changes made.
- Fix table sort handler attachment.
Fixed now: ~~I think there is something not quite right about the sorting logic, or perhaps the way it is attached to the tables.~~
~~Notice the incorrect placement of `115.99` in relation to the others. It looks like it is still using a string comparison. I'll try to fix that in another issue/PR.~~
> Inspired by wds mods

- data_capture/templates/data_capture/step_2.html
fixes #493
Now the valid price list rows table in Step 2 looks like
> improve Step 2 valid rows table markup

- Dockerfile
- requirements.txt
A few quick fixes:
* Fix #510 so the Dockerfile builds from scratch again
* Fix #515 so `manage.py dbshell` works
* Fix #517 to get rid of the unused `nose` and `django-nose` python packages
> Low-impact docker/requirements fixes

- data_capture/templates/data_capture/step_1_form.html
- frontend/source/sass/components/_upload.scss
- styleguide/templates/styleguide.html
Addresses #397. Both the text and color will change, though TBH I'm not sure I love the color change. Feedback very welcome!
> Make drag-and-drop widget's draggable state more noticeable

- frontend/source/sass/components/_page.scss
This fixes #535. It's basically just a port of https://github.com/18F/brand/pull/107 and it seems to get the job done.
> Fix sticky footer on ie11

- api/tests/test_api.py
- api/views.py
- contracts/models.py
- contracts/tests/test_contract.py
- contracts/tests/test_doctests.py
This adds a number of full text search tests and refactors things a bit by moving full text-related functionality from `api.views` into `contracts.models`.
Aside from increasing the robustness of our test suite, this is intended to collect all full-text search functionality in one place so that clients don't have to be concerned the concept of a `tsquery`. This will allow us to more easily migrate to [Django 1.10's full text search](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/search/) in the future (see #291 for more details).
> Add full text search tests, a few refactorings

- frontend/source/js/data-capture/step_1.js
- frontend/source/js/tests/index.js
- frontend/source/js/tests/step_1_tests.js
- package.json
This will fix #461.
We're adding [sinon](http://sinonjs.org/) to `package.json` for this.
To do:
> Add a test suite for step_1

- styleguide/templates/styleguide_ajaxform_example.html
Doh. I mistakenly wrote `.label` in the template when I should have written `.label_tag`.  Oof.
> fix typo in styleguide ajax form example.

- README.md
- hourglass/settings.py
- meta/management/commands/sendtestemail.py
- requirements.txt
This adds [dj-email-url](https://github.com/migonzalvar/dj-email-url), and also cherry-picks the [`manage.py sendtestemail`](https://docs.djangoproject.com/en/1.10/ref/django-admin/#sendtestemail) command from Django 1.9 (we'll remove it once we actually upgrade to 1.9).
It also adds documentation about configuring email to the readme.
(Context: I asked around on Slack and it looks like we use Mandrill for email sending, which is super easy to use and works via SMTP, so this PR should give us what we need.)
> Add support for sending email

- data_capture/forms.py
- data_capture/models.py
- data_capture/templates/data_capture/step_3.html
- frontend/date.py
- frontend/templates/frontend/date.html
- frontend/tests/test_date.py
- styleguide/date_example.py
- styleguide/templates/styleguide.html
- styleguide/templates/styleguide_date.html
- styleguide/templates/styleguide_date_example.html
- styleguide/tests.py
- styleguide/urls.py
- styleguide/views.py
This is an ~~experimental~~ attempt to fix #534 by using Django's [`MultiValueField`](https://docs.djangoproject.com/en/1.9/ref/forms/fields/#django.forms.MultiValueField) and [`MultiWidget`](https://docs.djangoproject.com/en/1.9/ref/forms/widgets/#django.forms.MultiWidget):
> ![screen shot 2016-08-18 at 7 48 31 am](https://cloud.githubusercontent.com/assets/124687/17772685/3174fc7a-6518-11e6-9959-86bbb7a055d7.png)
The implementation feels kind of weird, mostly because of the way Django's architecture forces a separation between form inputs and their labels. This makes it difficult to render a single multi-value field/widget as its own "component".
Another weirdness is that our date widget is meant to be placed in a `<fieldset>`, with the main "label" (e.g. "contract start date") in a …
> Implement SplitDateField and use it in step 3

- frontend/tests/test_qunit.py
- hourglass/urls.py
- styleguide/tests.py
I thought we had an issue filed for this but apparently we don't, or I can't find it.
This disables the `/tests/` ~~and `/styleguide/`~~ endpoint on production, purely for the sake of reducing the attack surface of the app.
~~I'm not sure how I feel about disabling the styleguide here, actually.  It's nice to be able to easily point to it as an example of a style guide (of sorts).  I guess we could add another environment setting that allows it to be exposed even when `DEBUG` is `False`, which we can enable on dev/staging but not prod...~~
~~Note that this PR is currently against #564 because that PR changes `urlpatterns` to be standard arrays. We can always re-target this PR to `develop` if that PR is merged before this one though.~~
> Only expose QUnit tests when DEBUG is enabled

- data_capture/forms.py
- data_capture/tests/test_views.py
- frontend/source/sass/components/_forms.scss
This fixes #499:
> ![screen shot 2016-08-18 at 7 41 41 am](https://cloud.githubusercontent.com/assets/124687/17772520/3f92318e-6517-11e6-893b-8fde2e63b5ed.png)
As discussed earlier, this UI requires the user to explicitly choose one of the radios, rather than defaulting to "not a small business", which is what happens when we use a single checkbox.
~~Currently this PR is against #561, but it doesn't actually *require* any of the functionality in that PR; I'm just doing it b/c there will be slightly annoying merge conflicts otherwise, since both PRs modify the `Step3Form`. (Due to the fact that github PRs can now change the base branch they're being merged into, though, it'll be easy to first merge #561 and later merge this one, if we want, which is nice.)~~
@hbillings does this look OK?
> Fix #499 by making 'is small business' radios.

- frontend/source/js/data-capture/ajaxform.js
- frontend/source/js/tests/ajaxform_tests.js
This is an attempt to fix #456 by using friendlier copy when network or other unexpected errors occur. I [asked on `#g-content`](https://18f.slack.com/archives/g-content/p1471615533000559) in Slack and they recommended this:
> <img width="456" alt="screen shot 2016-08-19 at 10 36 11 am" src="https://cloud.githubusercontent.com/assets/124687/17813480/8aeda8e2-65f9-11e6-8b32-96b4996e2333.png">
Because these errors happen so infrequently (um, hopefully), I think it's ok to keep using a standard `window.alert()` for now, but let me know if you disagree!
> Friendlier ajax error copy.

- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/upload_tests.js
- frontend/upload.py
This adds HTML5 form validation support to the upload widget so that users with supported browsers will see the following if they click "submit" without uploading a required file:
> ![screen shot 2016-08-22 at 5 03 20 pm](https://cloud.githubusercontent.com/assets/124687/17871627/5e96b048-688a-11e6-8b96-630b3c2a9ac1.png)
I think this is a more humane solution than graying out the submit button (#585) because it tells the user *why* they can't submit the form.  This could be particularly useful for larger forms, where there could be many reasons why they can't submit the form.
Aside from that, it's also technically much simpler than #585.
Of course, server-side form validation still works too, so users on older browsers will just get a slightly degraded experience.
To do:
> Add custom HTML5 form validation messaging for upload widget

- gulpfile.js
I'm experiencing some weird issues where every so often, it seems like JS bundle files aren't being written to my filesystem, at least not for a really long time.
Even regularly, though, there are at least 1-2 seconds in between when the last log message from gulp displays (e.g. `Finished 'lint' after 698 ms`) and when the JS bundle is actually written to the filesystem.  This means that I sometimes reload my browser page before the JS bundle has actually been written, which leaves me constantly paranoid about whether or not I'm viewing a page that has my latest code changes in it.
This PR just adds a log message at the end of writing the bundle, so I know when JS is actually written to disk, e.g.:
```
gulp_1  | [21:09:38] -> Rebundling frontend/source/js/tests/index.js
gulp_1  | …
```
> Log JS bundle writes

- Dockerfile
Blergh, in #526 we had to make a weird change to the dockerfile because the official Python Docker Hub image made `/usr/bin/python` inaccessible.
However, they just undid this in https://github.com/docker-library/python/pull/137, which made our weird change *break* our Dockerfile.  Awesome.
This undoes our weird change so that everything works again.
Blah.
> Fix Dockerfile to work again based on /usr/bin/python change blah.

- data_capture/admin.py
- data_capture/migrations/0003_auto_20160826_1930.py
- data_capture/models.py
- data_capture/templates/admin/data_capture/submittedpricelist/change_list.html
- data_capture/templates/admin/data_capture/submittedpricelistrow/change_list.html
- data_capture/tests/common.py
- data_capture/tests/test_admin.py
- data_capture/tests/test_models.py
This adds a new "submitted price list row view" admin view that allows the data administrator to view all *unapproved* price list rows and "mute" them if they're out of the ordinary:
> ![screen shot 2016-08-24 at 5 42 24 pm](https://cloud.githubusercontent.com/assets/124687/17949189/3f519ab0-6a22-11e6-8198-e424484f2e85.png)
Unfortunately, actually *approving* the price lists is a different step and can be accomplished from the "submitted price list view":
> ![screen shot 2016-08-24 at 5 42 57 pm](https://cloud.githubusercontent.com/assets/124687/17949200/454b3926-6a22-11e6-9d66-d266a02516cd.png)
I'm not a huge fan of this but it's what seems to be easily doable via django admin customization, alas.
Other changes:
* The admin detail view for submitted price lists still exists, but the "is …
> Make it possible to sort and "mute" individual price list rows

- hourglass/healthcheck.py
- hourglass/tests.py
- hourglass/urls.py
This fixes #625 by adding a `/healthcheck/` endpoint that checks to make sure the DB is synchronized and that redis/`rq` is working.
> Add /healthcheck/ endpoint

- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/upload_tests.js
Fixes #628.
Note that `<upload-widget>` actually only cares if it's in a `<form>` that is not an ajaxform.  If it's not in a `<form>` *at all*, then it actually doesn't care, which allows us to still test it and stuff without having to put it in a form.
> Degrade upload widget if not in ajaxform

- styleguide/templates/styleguide.html
Currently there are two references to `data-capture.min.css` in the styleguide, but there's no information on where that file is or where it comes from.  It's also a "weak" reference in that it's just plain text that will become confusing and out of date if we ever get rid of `data-capture.min.css`.  So instead, I've changed them both to link directly to the SCSS source files that contain the respective component(s).
> Strengthen references to CSS files in style guide and link to them

- frontend/source/js/data-capture/ajaxform.js
- frontend/source/js/data-capture/upload.js
- frontend/source/js/styleguide/index.js
- frontend/source/js/styleguide/web-component-link.js
- gulpfile.js
- styleguide/static/styleguide/styleguide.css
- styleguide/templates/styleguide.html
- styleguide/templatetags/styleguide.py
Ok, this is a bit funkadelic. It basically allows us to link to the source code of web components in our style guide.
As with the changes in #633, this is done both to help onboard new/rusty devs, but also to prevent doc rot: an alert is displayed if any of the web components don't exist, or if metadata about their location isn't found.
The only annoying part of this is that it requires us to add a `SOURCE_FILENAME` property to each web component's prototype that is set to `__filename` (the actual value of which is filled-in by browserify).
It'd be nice to make the QUnit test suite open the style guide in an iframe and verify that no errors are thrown, but I'd prefer to file that as a separate bug. For now just seeing a big alert when visiting `/styleguide/` if anything's broken should be …
> Mention, link to web components in style guide.

- .travis.yml
- data_capture/decorators.py
- meta/management/commands/ultratest.py
This adds the `ultratest` functionality described in https://github.com/18F/calc/issues/636#issuecomment-243761792 and runs `python manage.py ultratest flake8` during travis, fixing #636:
It also removes some unused imports from `decorators.py`, as `flake8` was actually failing 😄
> Remove unused imports, run flake8 during travis

- frontend/source/sass/components/_exceltables.scss
- frontend/source/sass/data_capture.scss
- styleguide/templates/styleguide.html
This adds some excel table styles that we can use to show users accessible "screenshots" of what the price list we need them to upload looks like.
It's intended for use in the following section of @hbillings's [mockups](https://gsa.invisionapp.com/d/main/#/console/8513772/182332256/preview):
> ![screen shot 2016-09-01 at 8 18 39 am](https://cloud.githubusercontent.com/assets/124687/18167110/c70ab1e4-701c-11e6-965e-81662909383c.png)
And here's what the new styles look like in the styleguide:
> ![screen shot 2016-09-01 at 8 20 26 am](https://cloud.githubusercontent.com/assets/124687/18167150/fb788f3c-701c-11e6-8a75-d67bf32f7880.png)
* I don't think overriding the base table styles, as I'm doing in this PR, is very maintainable, as it starts specificity wars and such.  We might want to …
> Add excel table CSS styles

- README.md
- cf.sh
- data_capture/admin.py
- data_capture/management/commands/initgroups.py
- data_capture/tests/common.py
- data_capture/tests/test_admin.py
- data_capture/tests/test_management_commands.py
- uaa_client/authentication.py
This fixes #668 by adding a `Data Administrators` role, which is created by a new `manage.py initgroups` command (based on [hive-django's `initgroups.py`](https://github.com/toolness/hive-django/blob/master/directory/management/commands/initgroups.py)).
As of this PR, authorization is set up as follows (this is taken from the `README.md` in this PR):
> * **Non-staff users** can upload individual price lists for approval.
> * **Staff users** can bulk upload price list data.
> * **Staff users** in the **Data Administrators** group can create and edit
>   users and assign them to groups. They can also review submitted price lists
>   and approve/unapprove them.
> * **Superusers** can do anything, but only infrastructure/operational
>   engineers should be given this capability. An initial …
> Add "Data Administrator" role for Django admin

- data_capture/panels.py
- data_capture/templates/data_capture/panels/docs.html
- hourglass/settings.py
- hourglass/urls.py
This adds a **Documentation** panel at the top of the panel list:
> ![screen shot 2016-09-08 at 8 43 19 am](https://cloud.githubusercontent.com/assets/124687/18349693/897e8060-75a0-11e6-9595-fe2fc9dfbf9a.png)
Specifically, it makes our style guide and test suite actually discoverable, so that should hopefully help new devs.
(I originally tried adding links to the style guide and tests in the top-right nav area of the base template, but I didn't like how much visual noise it added, so I resorted to a DjDT panel. Also, there's no way to embed links directly in the toolbar itself, which would've been preferable, so I resorted to a Documentation panel.)
> Add a Documentation DjDT panel

- data_capture/templates/data_capture/bulk_upload/region_10_step_2.html
- frontend/source/sass/components/_formbuttonrow.scss
- styleguide/templates/styleguide.html
Basically I had to also target `button[type="submit"]` in the rule to make `.form-button-row` buttons display as `inline-block`.
Also made a slight adjustment to the styleguide to put the Form Button Row section after the Form section (it was before, which is weird, logically).
Closes #691
> Fix form button row styling

- .travis.yml
We were ignoring selenium tests as of #331 during Travis builds because they often time out, per #330. However, when all the frontend-related code and tests were moved to `frontend/` I neglected to update the `--ignore` argument to `py.test` in our `.travis.yml`. This PR re-ignores selenium tests on Travis.
> re-ignore selenium tests in travis

- data_capture/forms/__init__.py
- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/step_4.html
- data_capture/tests/test_price_list_views.py
- data_capture/views/price_list_upload.py
**Note: This builds upon #707.**
This simplifies our price list form logic by storing the raw POST data from earlier steps in the session, rather than storing the same data in the session using a potentially error-prone custom serialization mechanism.
This also allows us to "resurrect" the actual `ModelForm`s for earlier steps when the user submits their data in step 4 and call their `save()` methods, saving us from having to assign data to the new model ourselves.
This new way of doing things also happens to fix #705.
I also fixed #711 because it was easy to fix along the way.
@hbillings can you take a look at this?  Does it make sense?
> Fix #705, #711, simplify price list form logic.

- data_capture/forms/__init__.py
- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/step_4.html
- data_capture/tests/test_price_list_views.py
- data_capture/views/price_list_upload.py
This improves [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) by using a `ModelForm` in step 1 of price list upload.
@hbillings does this look ok and make sense to you?  As with `Step2Form`, we're using a `ModelForm` to make things easy and DRY for us, but not actually saving the model until step 4.
> Use a ModelForm in step 1 of price list upload

- data_capture/templates/data_capture/messages.html
- frontend/source/js/data-capture/alerts.js
- frontend/source/js/data-capture/index.js
- frontend/source/js/tests/alerts_tests.js
- frontend/source/js/tests/index.js
- styleguide/ajaxform_example.py
- styleguide/templates/styleguide.html
- styleguide/templates/styleguide_ajaxform_example.html
This is an alternative attempt to fix #481.
Whereas #575 was a really complex attempt to fix the issue, this solution is far more simple. The following is suggested by  [WebAIM's Accessibility of Rich Internet Applications guide](http://webaim.org/techniques/aria/#keyboard):
> Additionally, it is often necessary to set focus to page elements. For instance, a form validation error message might be displayed as text (not a link or form element) within a page using scripting. Visual users can immediately see the error message. However, a screen reader user may not know that the new message is present. In order to set focus to the error message so it can be read by a screen reader, the message must be able to receive focus - something it cannot typically do unless it is a link or form …
> Add an <alerts-widget>

- data_capture/templates/data_capture/bulk_upload/region_10_step.html
- data_capture/templates/data_capture/bulk_upload/region_10_step_1.html
- data_capture/templates/data_capture/bulk_upload/region_10_step_1_form.html
- data_capture/templates/data_capture/bulk_upload/region_10_step_2.html
- frontend/source/sass/components/_steps.scss
Closes #596. Some copy and visual changes to the R10 uploader. (Ignore the incorrect steps bar; that should be fixed by a separate PR.)
> Bulk upload visual tweaks

- data_capture/tests/test_price_list_views.py
- data_capture/views/price_list_upload.py
This simplifies `data_capture.views.price_list_upload` a bit and improves its test coverage to 100%.
To see the test coverage for this file, you can run:
```
docker-compose run app py.test -k price_list_views --cov-report term-missing | grep data_capture/views/price_list_upload.py
```
Notes:
* I made `step_5` not require any kind of session information: all we're doing here is presenting the user with some information, so it's OK if they randomly decide to visit that URL.  It also moves the deletion of the price list from the session to step 4, which IMO makes the whole transaction a bit more atomic--and anyways, a GET request to `step/5` shouldn't change server state.
* Steps 1-3 will only accept `GET` or `POST` requests now.  Previously, other HTTP methods could potentially cause 500s …
> Improve price list views tests

- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/upload_tests.js
This fixes #710.
#710 was not caused by any kind of regression in #583--I think it may be a regression introduced way back in 1f04e7ff0295844900148d47d4e48b30252234f4 (part of #582) that we didn't discover until today.
I also discovered that #710 also only exhibits itself on Chrome, which is the only browser with native support for Custom Elements.
Basically, when dynamically injecting the HTML of an ajaxform into the page, we're first creating the DOM for the new form and then attaching it to the document tree.  In Chrome's case, this means that the web components in the HTML are upgraded *before* being attached to the document tree.  Once attached to the document tree, the `attachedCallback`s on custom elements are called in **tree order** (preorder, depth-first traversal), which …
> Make <upload-widget> work w/ funky upgrade timings.

- data_capture/templates/data_capture/bulk_upload/region_10_step.html
- data_capture/templates/data_capture/step.html
- data_capture/templates/data_capture/tests/my_step_1.html
- data_capture/urls.py
- data_capture/views/bulk_upload.py
- data_capture/views/common.py
- data_capture/views/price_list_upload.py
- styleguide/templates/styleguide.html
This supersedes #578 and fixes #413, as it was easier to just start a new PR instead of deal with the merge conflicts.  I'm also taking a slightly different approach that will make it easier to consolidate logic across all step-based workflows (i.e. region 10 bulk upload and price list upload).
Basically I'm doing this through the creation of a new `Steps` class, which encapsulates all the steps in a particular workflow.  Here's the docstring (which contains doctests that are verified during CI 🎉 ):
```
The `Steps` class makes it easier to consolidate the logic of
multi-step workflows.
The `Steps` constructor takes a format string representing what
the template path for each step looks like:
>>> steps = Steps('data_capture/tests/my_step_{}.html')
The `@step` view decorator can be used to …
```
> Make step-based workflows more accessibility-friendly, consolidate step logic

- data_capture/forms/price_list.py
- data_capture/tests/test_forms.py
- data_capture/views/price_list_upload.py
`price_list.Step3Form` used to have `schedule` as a user-facing field but we removed it in [the great form rejiggering of 2016](https://github.com/18F/calc/pull/583).  However, the field was still kept around in the actual form class.  This removes it as a field and instead expects the schedule to be passed-in to the form constructor.
Aside from making the code a bit more understandable, this will also help with #538, as it'll be easier to dynamically set the upload widget properties (accepted file types and help text) based on the schedule.
> Pass schedule into price_list.Step3Form constructor

- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/step_4.html
- data_capture/views/price_list_upload.py
This fixes #663.
It also makes `Step1Form` take care of automatically converting the schedule the user chose into a `BasePriceList` subclass, which should help with #737.
I also discovered that even though the fallback logic was working, the actual `schedule` property of the submitted price list was still being set to the user's preferred schedule (rather than the one we fell back to), so I fixed that too.
> Display preferred schedule during fallback

- frontend/source/js/data-capture/ajaxform.js
- frontend/source/js/tests/ajaxform_tests.js
- frontend/templatetags/qunit_fixture_data.py
- styleguide/ajaxform_example.py
- styleguide/templates/styleguide_ajaxform_example.html
This fixes the main remaining issue mentioned in https://github.com/18F/calc/issues/700#issuecomment-246176550 by having `ajaxform` check to see if a button/input with `type="submit"` is the currently focused element on the page before adding its name and value to a `FormData` instance.
The functionality can be manually tested through the ajax form in the style guide. I tried it on IE11, Chrome, Firefox, and Edge, and it works on all of them!  🎉
> Support multiple submit buttons in ajaxform

- data_capture/forms/price_list.py
- data_capture/schedules/base.py
- data_capture/schedules/fake_schedule.py
- data_capture/schedules/s70.py
- data_capture/templates/data_capture/price_list/step_3.html
- data_capture/templates/data_capture/price_list/upload_examples/fake_schedule.html
- data_capture/tests/test_base_price_list.py
- data_capture/views/price_list_upload.py
This fixes #538 by adding a `upload_widget_extra_instructions` property to `BasePriceList`.
It also lays a foundation for fixing #727 by adding an `upload_example_template` property and `render_upload_example()` method.  It doesn't actually provide the actual *content* for Schedule 70, though--we'll address that in a future PR.  (And it's fine to merge this now b/c the "I'm not sure what to upload" expander only appears if there's upload example content to fill it with.)
While I didn't add upload example content for schedule 70 (this is addressed in #754), I did add some for the fake schedule, which is only ever shown to developers:
> <img width="728" alt="screen shot 2016-09-15 at 9 58 13 am" src="https://cloud.githubusercontent.com/assets/124687/18552615/1f7083f4-7b2b-11e6-8a50-793ac7e68 …
> Allow schedules to provide upload examples and help text

- frontend/radio.py
- styleguide/radio_example.py
- styleguide/templates/styleguide.html
- styleguide/templates/styleguide_radio.html
- styleguide/templates/styleguide_radio_example.html
- styleguide/tests.py
- styleguide/urls.py
- styleguide/views.py
**Note: This is a PR against #751, not `develop`.**
This adds a USWDS-style radio widget.
> <img width="729" alt="screen shot 2016-09-15 at 2 38 59 pm" src="https://cloud.githubusercontent.com/assets/124687/18562558/37aae01e-7b52-11e6-9952-a758808816bf.png">
I wanted to add the pop-out link to the styleguide form as per #744 but it looks like #751 hasn't merged those changes in, so I left out the pop-out link.
Note that this just adds the widget and an example use of it in the style guide--it doesn't actually change #751 to use it.
> Add a USWDS radio widget

- data_explorer/templates/base.html
- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/upload_tests.js
- frontend/source/sass/components/_upload.scss
As mentioned in https://github.com/18F/calc/pull/654#r79152047, the `js` and `no-js` classes applied to `<html>` a la Modernizr actually violate the [Apply no style before its time](http://adaptivewebdesign.info/1st-edition/read/chapter-4.html) maxim of progressive enhancement.  In particular, it could be the case that this JS executes and applies the `js` style to the page, yet the data capture bundle fails to be retrieved for some reason, thus resulting in a broken page.
Beyond that, though, removing these classes, and our upload widget's reliance on them, actually *simplifies* our CSS and reduces the possibility of our site appearing to be broken.
Fortunately, removing the need for these classes was also easy, since the only component that relies on them is the upload widget.
> Get rid of html.js / html.no-js classes

- frontend/radio.py
- frontend/tests/test_radio.py
**Note: This is a PR against #751, not `develop`.**
This adds a test suite for `frontend/radio.py`.
It also slightly changes the implementation of `radio.py` to raise an error if the radio doesn't have an `id`: because of the fact that USWDS-style radios have labels as sibling elements instead of parents, the radio *needs* an `id` or else the browser won't be able to associate the label with it.  So now the radio widget raises an exception if it isn't given an `id`, instead of staying silent about it and generating broken markup.
> Add tests for radio.py

- styleguide/templates/styleguide.html
**Note: This is a PR against #751, not `develop`.**
This just adds a popout action to the radio example in the styleguide, similar to the ones added to other examples in #744.
@hbillings feel free to merge this into your PR if it looks good to you!
> Add popout action for radio styleguide example

- data_capture/forms/price_list.py
- data_capture/models.py
- data_capture/templates/data_capture/price_list/step_1.html
- data_capture/templates/data_capture/price_list/step_2.html
**Note: This is a PR against #751, not `develop`.**
This addresses @jseppi's comments at https://github.com/18F/calc/pull/751#issuecomment-247641856 and a few other things.
It resolves the help text margins by moving the help text back below the `<input>` field, which is where it was before the great rejiggering of #583. Here the bottom margin on `<p>` elements works to distance the help text from the next field, rather than from the input:
> <img width="474" alt="screen shot 2016-09-16 at 1 46 45 pm" src="https://cloud.githubusercontent.com/assets/124687/18595741/09a164be-7c14-11e6-823c-9a03a4bb03ee.png">
But I'm not sure if the move of the help text to be above the input in #583 was a deliberate decision, or just an accidental effect of the rejiggering.  Regardless, it's really easy to …
> Improvements to #751 (form input restyling)

- data_capture/templates/data_capture/price_list/step_4.html
Fixes #768
Also moves the `cancel` button to outside of the `{% if %}` block so that the price list submission can still be canceled when no valid rows are present in the selected file.
> Fix step 4 form-button-row markup

- data_capture/templates/data_capture/price_list/step_2.html
- data_capture/views/price_list_upload.py
Closes #737. Note that this doesn't display the schedule, in part because I'm no longer sure if we want to stick with displaying the schedule, or if we think we might want to shift to using SIN numbers a la the micropurchase.
> Show step 1 deets in step 2

- data_capture/schedules/s70.py
- data_capture/tests/test_s70.py
Small change to find the start row of the labor categories table instead of hardcoding `rownum = 3`. The new `find_header_row` works pretty naively by just returning the row index for the row that contains the first expected column heading (`"SIN(s) PROPOSED"`) in column 0.
To Do:
> Find Labor Categories start row index instead of hardcoding it

- README.md
Blerg.
The cloud deploy doesn't copy the `.env` file over, but the downside is that it means that we need to separately configure every container, which is a bit annoying, especially for environment variables like `DEBUG` that are shared across containers.
> improve cloud deployment YAML config.

- data_capture/templates/data_capture/price_list/step_1.html
- frontend/source/sass/base/_typography.scss
Closes #720. This sets a `max-width` of `72rem` on paragraph tags, which is 75% of the container's max width.
> Set max width for paragraphs

- frontend/source/js/data-capture/ajaxform.js
- frontend/source/js/tests/ajaxform_tests.js
This fixes ajaxform's interoperability with the browser's [back-forward cache](https://developer.mozilla.org/en-US/Firefox/Releases/1.5/Using_Firefox_1.5_caching), whereby on some browsers a page containing an ajaxform is shown in its post-redirect state when the user clicks their browser's "back" button.
Solution gleaned from [stack overflow](http://stackoverflow.com/a/13123626).
To reproduce the bug this is fixing, do the following on Safari (probably in IE as well, according to yesterday's user research session):
1. Visit any ajaxform, e.g. `/styleguide/ajaxform`.
2. Fill the form out properly and click submit.
3. Click the back button.
You should see the ajaxform in its "loading" (i.e. faded out) state.
> Fix ajaxform interop w/ back-forward cache

- frontend/source/js/data-capture/date.js
- frontend/source/js/data-capture/index.js
- frontend/source/js/tests/date_tests.js
- frontend/source/js/tests/index.js
- frontend/source/sass/components/_date.scss
- frontend/source/sass/main.scss
- frontend/templates/frontend/date.html
- styleguide/static/styleguide/styleguide.css
- styleguide/templates/styleguide.html
During user testing today someone tried typing `4/28/1986` into a date widget, but was confused when it didn't work.  This PR adds a `<uswds-date>` custom element which detects if the user presses `/`, `-`, or `.` and, if so, advances to the next field if applicable.
To do:
> add <uswds-date> custom element that focuses on next widget on "/" key

- styleguide/static/styleguide/styleguide.css
This uses the [`:target`](https://developer.mozilla.org/en-US/docs/Web/CSS/:target) CSS pseudo-selector to show the user where the section they just navigated to is.
> Show highlight animation when section of styleguide is navigated to

- frontend/source/sass/components/_steps.scss
This salvages the step fade-in from #793 as a CSS animation.
If the user's browser doesn't support CSS animations, this PR has no effect (in other words, the current step will still appear "filled-in" from the start, rather than appearing "empty" and never being "filled").
> Fade-in current step

- hourglass/templates/admin/base_site.html
Wraps the "Region 10 Upload" link in the Admin site header in a permissions check, per https://github.com/18F/calc/pull/798#issuecomment-249223920
> Wrap Region 10 Upload link in perms check

- frontend/source/sass/components/_expandablearea.scss
This fixes #797 and adds a dinky "fade in" CSS transition when expanding so that users can distinguish what's just been added from the rest of the document.  (Ideally this would be a slide but I dunno how to do that without some fancy JS, and we've got bigger fish to fry anyhow.)
Browsers without support for CSS animations will just see the content appear instantly (i.e., the current behavior).
This PR also refactors the SASS to use nesting.
> make <expandable-area> work in print, add CSS transition.

- data_explorer/templates/index.html
- frontend/tests/test_selenium.py
This fixes #813. It also makes our radios under the search field in the data explorer visible again:
> ![radios](https://cloud.githubusercontent.com/assets/124687/18893152/a5fc657e-84da-11e6-87bb-9d4189ce5e64.png)
> Fix selenium tests and radios in data explorer

- data_capture/admin.py
- data_capture/templates/admin/data_capture/add_user_form.html
- data_capture/tests/test_admin.py
This simplifies the "add user" form:
> ![add-user](https://cloud.githubusercontent.com/assets/124687/18854420/512fe91a-8419-11e6-86f4-2a23c2399d97.png)
When submitted, the uniqueness of the email is checked; if a user already exists with the email, an error message with the text "That email address is already in use." is displayed.
If the email is unique, then a username is automatically generated by [slugifying](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.text.slugify) the first several characters of the username part of the email address, and adding a number at the end if needed for uniqueness.  This should be OK since users never see their usernames, and admins will only ever see the usernames in the admin UI.
The "change user" form has also been modified to ensure …
> Enforce uniqueness of user email, simplify user add form.

- styleguide/static/styleguide/styleguide.css
This just re-aligns the styleguide section headers. We're now defining them in terms of `em` so hopefully we don't need to adjust them as styles change anymore.
> Adjust margin-left of styleguide section headers

- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/step_1.html
- data_capture/templates/data_capture/price_list/step_2.html
- frontend/source/sass/components/_forms.scss
- frontend/templates/frontend/fieldset.html
- frontend/templatetags/frontend.py
~~**Note: This is a PR against #817, not `develop`.**~~
This attempts to use `<legend>` for date widgets and radio button selects for reasons explained in https://github.com/18F/calc/pull/817#issuecomment-250201585.
The styling remains the same as before, though I had to wrap the `<legend>` in a `<span>` to get there because [bleh](http://stackoverflow.com/a/3973527).
> Use <legend> where appropriate

- data_capture/__init__.py
- data_capture/tests/test_xlsx_security.py
- requirements.txt
This is an alternate approach to fixing #749. It just calls `defusedxml.defuse_stdlib()` whenever `data_capture` is imported, and adds a test to verify that `xlrd` is using it, and that we aren't vulnerable to the [Billion Laughs](https://en.wikipedia.org/wiki/Billion_laughs) exploit.
This means that `xlrd.open_workbook()` can now throw a `defusedxml.common.EntitiesForbidden` exception, but that should be fine since our schedule 70 gleaner catches *any* exceptions thrown from `xlrd.open_workbook()`.
To do:
> Use defusedxml and ensure xlrd is using it

- frontend/templates/frontend/fieldset.html
Arg, NVDA (and possibly other screen readers) *do* work with `<legend>` elements, but only if they're direct descendants of `<fieldset>`s, i.e. not wrapped in `<span>`s so we can style them.  So this adds a `<legend class="sr-only">` for the screenreaders and an `<label aria-hidden="true">` for the sighted folks.
😞
> Make <legend>s work on NVDA

- data_explorer/templates/base.html
- frontend/source/js/common/ga.js
- frontend/source/js/data-capture/expandable-area.js
- frontend/templates/frontend/safe_mode/script.js
This addresses some of the user stories outlined in #839:
* It defines [custom dimension](https://support.google.com/analytics/answer/2709828?hl=en#configuration) index 1 to be the user ID of the currently logged-in user.  This isn't PII by itself so we should be fine storing it in google analytics.
* It defines custom dimension index 2 to be `safe mode enabled` if safe mode is enabled.
* Whenever the user is shown the safe mode opt-in, an [event](https://support.google.com/analytics/answer/1033068?hl=en) of category `safe mode` and action `show` is triggered.
* Whenever the user expands or collapses an `<expandable-area>`, a custom event of category `expandable area` and action `expand` or `collapse` and the label of the expander (i.e. the text the user clicked on) is triggered.
* Moves …
> Improve google analytics tracking

- .travis.yml
- README.md
- frontend/tests/test_qunit.py
- frontend/tests/test_selenium.py
- frontend/tests/utils.py
- selenium.md
> Improve selenium testing

- frontend/templates/frontend/safe_mode/ui.html
This fixes #854. Note that internally, within the codebase, we're still calling it "safe mode" because it's (A) shorter to type and (B) never exposed to end-users.  Also, it is a huge pain to rename all that stuff. 😉
> Rename 'safe mode' to 'compatibility mode', other writing lab fixes

- data_capture/templates/data_capture/price_list/step_3_errors.html
- data_capture/tests/test_price_list_views.py
- data_capture/views/price_list_upload.py
This fixes #804.
I basically implemented the mockup @hbillings described in https://github.com/18F/calc/issues/804#issuecomment-250782942:
Additional notes/caveats/adjustments:
* The error alerts no longer hyperlink the phrase "try uploading it again" to step 3.  An alternative might be to leave them hyperlinked, but change the behavior so that the page scrolls down to the upload form and gives it a temporary visual highlight to attract the user's attention to it.
* If no valid rows were found, we don't display the text "Otherwise, we'll discard the rows with problems when we upload your original spreadsheet", since continuing without fixing the errors isn't an option. An alternative might be to display entirely different text if the user *must* upload a fixed form to continue--for …
> Embed upload form in /data-capture/step/3/errors

- frontend/tests/test_qunit.py
- frontend/tests/test_selenium.py
This uses the instructions in [Building links to test results](https://wiki.saucelabs.com/display/DOCS/Building+Links+to+Test+Results) to display a link to sauce labs results that is visible in the `stdout` log when selenium tests fail.
It also hides successful test results in QUnit, so that hopefully information relevant to the failing test(s) is visible in the Sauce Labs screencast.
You can see what this looks like in #896, which adds a trivial failing test to the build:
I guess it's not super easy to notice, but it's there if you know where to look... Definitely a step up from not having any idea and needing to scour the Sauce Labs logs for clues.
Here's what the QUnit test output looks like when we only show failing tests:
> Link to Sauce Labs results when selenium tests fail

- frontend/source/js/common/ga.js
- frontend/source/js/tests/ga_tests.js
- frontend/source/js/tests/index.js
From [how analytics.js works](https://developers.google.com/analytics/devguides/collection/analyticsjs/how-analyticsjs-works):
> The JavaScript tracking snippet defines a global `ga` function known as the "command queue". It's called the command queue because rather than executing the commands it receives immediately, it adds them to a queue that delays execution until the analytics.js library is fully loaded.
The same page later states:
> Once the analytics.js library is loaded, it inspects the contents of the `ga.q` array and executes each command in order. After that, **the `ga()` function is redefined**, so all subsequent calls execute immediately.
(Emphasis mine.)
The fact that `ga` is *redefined* means that we shouldn't be caching it in our `common/ga` module, because if `ga` fails …
> In 'common/ga', always proxy to window.ga() instead of permanently caching it

- frontend/tests/test_selenium.py
This is an attempt to maybe fix #883 via the strategy described in https://github.com/18F/calc/issues/883#issuecomment-252263117.
Basically, before any specific Selenium test cases are run, the test harness repeatedly attempts to load `/about/` for 10 seconds. [Sauce labs output is available here.](https://saucelabs.com/beta/tests/85673f76e2a447f68ab0d59dc8f69872/watch#10)
Thoughts @jseppi?
> Ensure gateway works when testing on sauce labs

- frontend/source/js/data-capture/smooth-scroll.js
Whoops, should have caught this in the #884 review. Just replaced repeated conditions with `IS_SUPPORTED`.
> use IS_SUPPORTED in check to activate

- frontend/source/sass/components/_buttons.scss
Currently, not all of our buttons have great focus styling. Here's me tabbing through all the [buttons in our styleguide](https://calc-dev.apps.cloud.gov/styleguide/#buttons):
> ![before](https://cloud.githubusercontent.com/assets/124687/19352749/ff88492c-912e-11e6-95c3-af452c3b2fc9.gif)
So it's very hard/impossible to tell when default, disabled, gray, and link buttons are in focus, which makes interaction particularly challenging for keyboard users.
This PR changes styling so it's easy to tell when any button is focused:
> ![after](https://cloud.githubusercontent.com/assets/124687/19352825/4630aedc-912f-11e6-957f-39f823fc9e18.gif)
> Improve button focus styling

- uaa_client/templates/logged_out.html
I guess something that maybe looks not great is that the `.alert` spans the entire page width.
Closes #511
> spruce up the Logged Out page

- frontend/source/js/data-capture/smooth-scroll.js
- frontend/source/js/tests/smooth-scroll_tests.js
This fixes #921.
I'm opting to not use jQuery for this new code to make it easier to eventually decouple this module from jQuery and publish it on npm.
To do:
> Remember last known scroll position and go to it when reloading page

- frontend/source/js/tests/smooth-scroll_tests.js
This fixes our QUnit tests on PhantomJS by simply ignoring the parts of our smooth scroll tests that use `scrollTop`.
(They weren't triggering Travis fails because we're now running the QUnit tests against IE11.)
> Fix qunit tests on phantomjs

- styleguide/templates/styleguide.html
This fixes #923 by expanding the introduction of the style guide to include a link to the 18F Content Guide and information about our progressive enhancement strategy:
> <img width="604" alt="screen shot 2016-10-18 at 10 02 36 am" src="https://cloud.githubusercontent.com/assets/124687/19480867/0616a24a-951a-11e6-88a1-fbebb8f3acbb.png">
> Expand introduction to styleguide

- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/upload_tests.js
This fixes #919, as well as another bug that hasn't been documented yet: if the user drags and drops a file into the widget, and then drags a file over the widget and then out of the widget, the drag indication wouldn't go away, because we weren't resetting `dragCounter` on the `drop` event.
> Fix problems w/ upload widget drag/drop indication

- data_capture/schedules/base.py
Very minor correction: `raise NotImplementedError()` instead of `return NotImplementedError()`
> raise exception instead of returning it

- frontend/source/sass/components/_safemode.scss
- styleguide/templates/styleguide.html
This documents the compatibility/safe mode in the style guide.
Most of the copy was taken from the description of https://github.com/18F/writing-lab/issues/197.
> Document compatibility/safe mode in style guide

- styleguide/ajaxform_example.py
Well, I was going to do this real quick, but I am unable to get the `<alerts-widget>` example in the Style Guide (http://app.calc.docker/styleguide/ajaxform) to actually show the alerts widget. Any ideas, @toolness?
And then I noticed that it appears there is already a rule to remove the focus from `alert-widget`: https://github.com/18F/calc/blob/develop/frontend/source/sass/components/_alerts.scss#L40 (added by @hbillings in 82210e35ad247ef28cd52b7e308badee51744ff9).
So, I just corrected a minor typo I found.
Closes #932
> Fix minor typo ~~Remove focus outline from <alerts-widget>~~

- styleguide/templates/styleguide_ajaxform_example.html
This fixes #968 so that the example ajaxform uses fieldsets and errors look better:
> ![2016-10-26_14-44-19](https://cloud.githubusercontent.com/assets/124687/19739913/bafe62ee-9b8a-11e6-8f2e-3073c3f1af6c.png)
> Use {% fieldset %} in ajaxform example

- frontend/source/js/data-capture/alerts.js
This fixes #967. For an explanation, see https://github.com/18F/calc/issues/967#issuecomment-256464907.
> Make AlertsWidget extend HTMLElement

- frontend/source/js/data-explorer/explorer.js
This is an attempt to fix #924 by setting the [GA `location` field](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#location) and issuing a `pageview`.
* The **GA Single Page Application Tracking guide** specifically advises us to [not update the document location](https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications#do_not_update_the_document_location), but this seems weird to me because that's all we're changing, and we really *want* those new querystring arguments to be tracked by GA. And since we're not using GA's campaign fields (e.g. `utm_source`, `utm_campaign`, etc) I don't *think* it should break its session tracking...
* As with the ajaxform improvements in #869, the way this is currently …
> Set GA location, send pageview on search

- hourglass/templates/admin/base.html
Fixes the weird issue that looked like a 1px pad underneath the navigation tabs on `/admin` pages.
During a screenhero session with @hbillings, we realized the actual problem was that the Lato custom typeface was not being included in the admin base template.
Before:
After:
> Include Lato in Admin base template

- hourglass_site/templates/base.html
This fixes #1009 on the legacy/prod branch, so that we can deploy the change to calc.gsa.gov before we receive the ATO for CALC 2 if needed.
> Replace ethnio script on master (aka legacy/prod) branch

- data_explorer/templates/base.html
This fixes #1009 on the `develop` (aka CALC 2) branch.
~~Um, it is being applied to the `develop` branch though. Should I also backport it to `master` so we can get it on calc.gsa.gov ASAP?  Or since it looks like we're getting the ATO real soon, should we hold back on backporting?~~ Backported this to legacy/prod (aka CALC 1) in #1011.
> Add new ethnio script

- data_capture/templates/price_lists/details.html
Relatively minor fix. The `if` statement in the details template was checking the wrong condition for showing the table of existing price list rows.
> check price_list_rows instead of gleaned_data.valid_rows

- hourglass/tests/tests.py
One of our tests is to ensure that the default value of `settings.GA_TRACKING_ID` is an empty string when it's not defined already in the OS environment.  However, if it *is* already defined in the OS environment (which is the case on my dev system right now), there's actually no way for us to test this, so we'll skip it.
> Skip GA_TRACKING_ID test if defined in env

- README.md
This just adds a **Related repositories** section at the top of the README that currently only contains one item, a link to https://github.com/18F/calc-analysis.
I figured I'd put it at the top of the README since it's probably useful to non-technical audiences, while the vast majority of the rest of the README is specific to technical audiences... So I didn't want it to get buried in all the technical mumbo-jumbo.
> Add link to 18F/calc-analysis in readme

- docker_django_management.py
Fixes #1003.
Note that this doesn't actually seem to make the output go to `stderr` by default: in order to really send `stderr` in the Docker container to `stderr` in the host, you'll need to pass the [`-T` option to `docker-compose run`](https://docs.docker.com/compose/reference/run/), e.g.:
```
docker-compose run -T app python manage.py dumpdata > boop.json
```
Um, except that the output is very inconsistent, which seems to be due to https://github.com/docker/compose/issues/3267. Weird.
> Make docker_django_management.py output to stderr

- gulpfile.js
This reduces repetition in our gulpfile to make it easier to add new JS bundles for individual pages as we see fit, as per https://github.com/18F/calc/pull/1043#discussion_r89008703.
I'm not super happy with the way I refactored this but I think maybe we can refactor it more in the future to make it better. Right now it has been refactored to be sort of grunt-ish, in that `bundles` is now a configuration object that we iterate through to define actual tasks and stuff.  Hrm.
> Refactor gulpfile to make it easier to add new bundles

- frontend/source/js/data-capture/upload.js
- frontend/source/js/tests/upload_tests.js
- frontend/source/sass/components/_upload.scss
- frontend/tests/test_upload.py
- frontend/upload.py
- styleguide/templates/styleguide.html
- styleguide/views.py
As per yesterday's coworking discussion, this PR provides functionality that allows a progressively-enhanced upload widget to *appear* to be "pre-populated" on page load, with a fallback for the baseline experience:
> ![screen shot 2016-11-23 at 7 47 07 am](https://cloud.githubusercontent.com/assets/124687/20562395/597eefde-b151-11e6-8023-618da0240e55.png)
Note that this PR does *not* actually use this functionality anywhere yet (other than the styleguide). That comes in a later PR!
To do:
> Support fake filenames in upload widget

- data_explorer/templates/base.html
- data_explorer/templates/index.html
- data_explorer/views.py
- frontend/templates/frontend/safe_mode/script_tag.html
- hourglass/urls.py
This is a quick fix that adds some basic defense in-depth to mitigate any latent XSS vulnerabilities in the data explorer index page *only* (e.g. #1060).  It's a very broad CSP rule that basically allows anything except scripts that we "bless"--specifically, ones that originate from us/DAP/ethnio/GA and inline scripts that we've added a `nonce` attribute to.
The CSP doesn't actually do anything particularly helpful on IE or Edge or any [other](http://caniuse.com/#feat=contentsecuritypolicy2) browsers that only support CSP version 1, because it takes advantage of the [nonce-source](https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/) feature of CSP 2 to make it easy for us to quickly add CSP without having to un-inline all our scripts.
Note that Firefox applies CSP …
> Add nonce-based CSP to index page only

- data_capture/forms/__init__.py
- data_capture/forms/price_list.py
- data_capture/templates/data_capture/price_list/step_4.html
- data_capture/tests/test_forms.py
- data_capture/tests/test_price_list_upload_views.py
- data_capture/views/price_list_upload.py
- frontend/source/js/data-capture-price-list-upload-step-4/index.js
- gulpfile.js
This attempts to add an **Edit** button below the vendor and contract details section of step 4 of price list upload.
If the user is in safe mode (or doesn't have JS) they are sent to a version of the page with an edit form on it.  Otherwise, the vendor/contract details slide up and are replaced by a form:
> ![expandable-area2](https://cloud.githubusercontent.com/assets/124687/20397077/6464f0a0-acb6-11e6-9c19-bdf2d30a59e6.gif)
If the user submits anything invalid, they are re-shown step 4 with the edit form already displayed and the appropriate error(s) highlighted.
Otherwise, If their changes are valid, the price list is submitted and the user moves to step 5. (We could potentially change this to re-show step 4 without the edit form, so that the user is forced to re-verify that …
> Add edit button on step 4 of price list upload

- .eslintrc
- frontend/source/js/data-capture/ajaxform.js
- frontend/source/js/data-capture/alerts.js
- frontend/source/js/data-capture/custom-event.js
- frontend/source/js/data-capture/expandable-area.js
- frontend/source/js/data-capture/upload.js
Currently our eslint configuration doesn't ensure that `import` statements in our code are actually valid, so if we have e.g.:
```js
import nonExistentMethod from './util';
```
then eslint won't complain, and the code will actually run fine, until `nonExistentMethod` gets used somewhere, at which point it will be `undefined`.
This just enables an eslint rule to ensure that the `import` statements make sense, so our test suite will fail if they don't.  It also fixes some warnings raised by the addition of the new rule.
> make eslint ensure import statements are valid.

- frontend/source/js/data-explorer/explorer.js
- frontend/source/js/data-explorer/histogram.js
- frontend/source/js/data-explorer/table.js
- frontend/source/js/data-explorer/util.js
These are a few more refactorings that try to make the data explorer a little bit easier to understand:
* In `table.js` and `histogram.js`, all global CSS selectors are now constants defined at the top of the file. I thought this might make it easier to figure out what global state the modules were modifying. I wanted to do this with `explorer.js` too but there were just way too many global selectors. (Outside of these three files, none of the modules reference global CSS selectors.)
* Made  `table.js` better encapsulated by moving `parseSortOrder` from `util.js` into it, and also moving some table-specific code out of `explorer.js` into it.
> A few more data explorer refactorings

- data_explorer/views.py
This works around #1092 by disabling CSP 2.0 on the data explorer index page.
> Disable CSP because New Relic sucks.

- .travis.yml
- frontend/crotchety.py
- frontend/tests/test_crotchety.py
- hourglass/settings.py
This is an alternative to #1141 that tries to fix #1136 by implementing a development-only static file storage backend whose `url()` method throws an exception when passed a non-existent file name, just like the @$💥%#💩!ing `CompressedManifestStaticFilesStorage` does in production.
> Add frontend/crotchety.py to simulate production static file storage.

- styleguide/static/styleguide/styleguide.css
- styleguide/templates/styleguide.html
- styleguide/templates/styleguide_ajaxform.html
- styleguide/templates/styleguide_base.html
- styleguide/templates/styleguide_date.html
- styleguide/templates/styleguide_radio.html
- styleguide/templates/styleguide_section.html
This fixes #1115.
To do:
> ![borderz](https://cloud.githubusercontent.com/assets/124687/21272612/fccc219a-c38d-11e6-9c87-3655c7c33e2d.png)
> Clean up styleguide

- frontend/source/js/data-capture/smooth-scroll.js
- frontend/source/js/tests/smooth-scroll_tests.js
This fixes #1162 by storing the last scrolled-to position on the page before navigation in `window.history.state` instead of using `window.sessionStorage` and keying off the URL.
> Store scrollTop in history.state instead of sessionStorage

- frontend/source/js/data-capture/smooth-scroll.js
- frontend/source/js/tests/smooth-scroll_tests.js
This builds on the smooth scroll functionality to smoothly scroll the page on initial page loads, if there's a valid id in the location hash.
If this seems OK, we could additionally improve it by making it auto-scroll to `#messages` (or other configurable default id) if it exists *and* there's no other id defined in the location hash, as suggested in https://github.com/18F/calc/pull/1089#discussion_r93454626.
> Smoothly scroll to location hash on new page load

- CHANGELOG.md
This adds a changelog file in the form of [keepachangelog.com](http://keepachangelog.com/).
I noticed that the CALC 1.0 team actually made [a few releases](https://github.com/18F/calc/releases) and provided some release notes for them, so I copied them out and put them in the file so we have some nice history to start with.
Currently the "unreleased" section actually contains the big CALC 2.0 release, because we haven't yet tagged a release for our new version (at least, not one that uses semantic versioning). Once we do that, we can update the changelog!
> Add CHANGELOG.md.

- hourglass/healthcheck.py
- hourglass/tests/tests.py
**Note: This is a PR against #1193, not `develop`.**
This adds the version number to the `/healthcheck` endpoint.
I'm actually a bit conflicted about whether this is a good place to put the version (it doesn't have to be the *only* place we put it, of course).  It's not *directly* related to the health of a deployment, but at the same time, it does give some significant *context* with which one could judge the deployment's health, so... I dunno. Feel free to just close this PR if you don't like it.
> Report version number in /healthcheck.

- meta/management/commands/ultratest.py
Closes #1192 
On fail:
On success:
> Add large Fail and Success messages

- README.md
- docker-compose.local.yml
Since we're likely going to add some kind of HTML email support soon (see #1208) and it's annoying to read plain-text emails in the terminal that's outputting all the other log information for the app, I thought it might be useful to add a [MailCatcher](http://mailcatcher.me/) container for development.  This exposes the app on port 1080, so that a developer can just go there to easily see any emails sent from the app, and browse them in their HTML and plain text representations:
> ![screen shot 2017-01-09 at 6 36 48 pm](https://cloud.githubusercontent.com/assets/124687/21788055/b9d365c2-d69a-11e6-8964-e7a243998d23.png)
(There's no "HTML" tab in the above screenshot because we're currently only sending emails in plain text.)
I decided to use …
> Add a MailCatcher container for development

- .travis.yml
- Dockerfile
- data_capture/tests/test_price_list_views.py
- hourglass/tests/test_configuration.py
- runtime.txt
- uaa_client/tests/test_views.py
This upgrades CALC to work on Python 3.5, fixing #766.
The upgrade actually surfaced a bug in two of our tests: we were calling `assert` methods on `Mock` objects that were  introduced in Python 3.6, but Python 3.4 wasn't throwing an `AttributeError` on them because the mock assumed any nonexistent method calls were mock calls!  Fortunately they fixed this in [Python bug 21238](https://bugs.python.org/issue21238) so that a `Mock` *would* throw an `AttributeError` if `assert` (or a common misspelling, `assret`) was in the attribute name, which thus made our tests break.
> Upgrade to Python 3.5

- README.md
When setting up an EC2 instance just now, I forgot about the fact that the default EC2 instance type of `t2.micro` is way too small to run CALC (`manage.py load_data` crashes).  So I provided an example snippet for EC2 that uses `t2.large` so that next time we need to spin up an EC2 instance, we won't waste 20 minutes spinning up the wrong instance type. :)
> Document 'docker-machine create' example w/ amazonec2.

- data_capture/schedules/base.py
- data_capture/tests/test_base_price_list.py
This makes our `BasePriceList` class an official [abstract base class](https://docs.python.org/3/library/abc.html), which means that subclasses deriving it *must* implement all abstract methods in order to be instantiated.  Aside from providing some protection against bad/outdated code, it should also make it easier for us to add mypy annotations in the future.
> Make BasePriceList an abc.ABCMeta

- hourglass/changelog.py
- hourglass/templates/changelog.html
- hourglass/tests/test_changelog.py
- hourglass/urls.py
- requirements-dev.txt
- requirements.txt
This follows [cloud.gov's convention](https://cloud.gov/updates/) of exposing a human-friendly changelog at `/updates/`:
It is not *particularly* human-friendly right now but we can improve it!
> Expose changelog view at /updates/

- gulpfile.js
- package.json
Apparently there is a module called [`uglifyify`](https://github.com/hughsk/uglifyify) (not to be confused with `uglify`) which allows us to fix #1244.  See its [motivation/usage](https://www.npmjs.com/package/uglifyify#motivationusage) section for an example.
Its README *does* still encourage the use of uglify on its own, since apparently there are optimizations it can do that uglify*ify* cannot.
If we ever switch to webpack, this whole thing will not be nearly as confusing.  We just use its [`DefinePlugin`](https://webpack.github.io/docs/list-of-plugins.html#defineplugin), make sure minification is enabled, and we're done.
> Use uglifyIFY to excise unused dependencies from bundle

- hourglass/changelog.py
- hourglass/templates/changelog.html
- hourglass/tests/test_changelog.py
This attempts to make `/updates/` a bit friendlier to non-developers by removing the expository text from `CHANGELOG.md` (which mentions things like keepachangelog.com and semver) and replacing it with expository text in the `changelog.html` template:
> ![screen shot 2017-01-18 at 8 21 40 am](https://cloud.githubusercontent.com/assets/124687/22065636/2cf9bf84-dd57-11e6-96e9-ba1163dffb59.png)
It also renames the page from "Change Log" to "Updates", following the lead of [cloud.gov/updates/](https://cloud.gov/updates/). It also just sounds less technical.
Also, if the "Unreleased" section is empty--which it should be on production deploys--then it is removed entirely from the page.
> Make /updates/ friendlier to non-developers

- deploy-travis.sh
Because we have a fairly slim memory-allocation-margin, our production deployment will actually fail due to exceeding that allocation if the number of app instances is not scaled back before the `cf zero-downtime-push`. 
This PR mitigates the issue by scaling the app instances down to 1 before pushing the new version.
Note that the new version will launch with the number of instances specified in its corresponding manifest.yml (2 in the case of calc-prod).
> Scale down instances to 1 during deployment

- hourglass/settings.py
- hourglass/tests/tests.py
This attempts to at least temporarily resolve #1257 by explicitly telling downstream caches to never cache our dynamic views by default.
In order to send the `Cache-Control` headers we also enable [Django's site-wide cache middleware](https://docs.djangoproject.com/en/1.10/topics/cache/#the-per-site-cache).
Because we're setting the default expiry via [`CACHE_MIDDLEWARE_SECONDS`](https://docs.djangoproject.com/en/1.10/ref/settings/#std:setting-CACHE_MIDDLEWARE_SECONDS), individual views and middlewares (like whitenoise, which serves our static files) should be able to override the default, so that we can still leverage CloudFront for resources that we actually *want* to cache.
Note, though, that because we're actively preventing our views from being cached by default, it might actually …
> Send 'Cache-Control: max-age=0' by default

- styleguide/templates/styleguide.html
- styleguide/views.py
Hey @hbillings, this is a PR against your PR #1245 to make the error table in the styleguide render using your same code for the s70 error table, so that it won't go stale.  Feel free to modify at will or reject this PR outright.
> Make styleguide reuse s70 error table template.

- data_capture/schedules/s70.py
- data_capture/templates/data_capture/price_list/tables/schedule_70.html
This is against #1245 and displays the header row by iterating through all the fields in an empty `Schedule70Row` instance.
> Generate <th> by iterating through form fields

- api/tests/test_api.py
- api/views.py
If a comma-separated list of search terms contains an empty string as one of the terms (e.g. due to a trailing comma) then the "contains phrase" search will actually return all results because every labor category contains the empty string.
This fixes that, I think.
> Don't allow 'contains phrase' searches w/ empty string terms

- data_explorer/templates/_footer.html
- data_explorer/templates/about.html
- frontend/source/sass/components/_footer.scss
Closes #1273
In this PR, I've moved the icon credits out of the footer template and down to a new section at the bottom of the About page. I manually searched Noun Project to figure out which icon came from whom. One interesting thing is that I couldn't find anything by "Paulo Sá Ferreira" but I did find that our Roof icon seems to come from a previously unmentioned author ("Symbolon"). I followed https://thenounproject.zendesk.com/hc/en-us/articles/200744853-How-do-I-credit-multiple-icons- for how to do the attribution.
> Move icon credits to About page

- .gitignore
- Dockerfile
- Dockerfile.cloud-extras
- README.md
- docker-compose.local.yml
- docker-compose.yml
- docker-services.yml
This helps mitigate #1322 by making things more efficient for the vast majority of use cases, and making things a bit more annoying for cloud deploys.
We do this by moving the `COPY . /calc/` and `RUN gulp build` commands out of the standard `Dockerfile`.  Instead, cloud deployers will need to create a new Dockerfile that concatenates the standard `Dockerfile` and a `Dockerfile.cloud-extras`, the latter of which contains the two missing commands, and then point to this new Dockerfile in their `docker-compose.override.yml`. This process is fully detailed in `README.md`.
Note that in order to accomplish this, I had to upgrade all our docker-compose files to [version 2](https://docs.docker.com/compose/compose-file/#/versioning).  (Uh, I also didn't realize until adding that link, that …
> Only copy source code & run gulp for docker cloud deploys

- RELEASE.md
This mentions not to squash or rebase the release candidate PR into `master`, as that was the cause of the schism which prompted https://github.com/18F/calc/pull/1336#issuecomment-278130292 and #1337.
> Mention not to squash or rebase in RELEASE.md.

- package.json
This ~~fixes~~ works around #1343 by pinning our `gulp-clean-css` to the most recent working *deprecated* version, 2.3.2.  I don't think we can actually upgrade to 3.0 yet because of the breakages documented in #1343, so we might want to leave fixing that to a different PR.
> Pin gulp-clean-css to 2.3.2

- requirements.txt
New version of `defusedxml` was released today - see changelog at https://github.com/tiran/defusedxml#defusedxml-050rc1.
This should allow us to proceed with upgrading to Python 3.6: https://github.com/18F/calc/pull/1265.
> Upgrade defusedxml to 0.5.0

- .travis.yml
- Dockerfile
- requirements-temp-extras.txt
In #997 and #1353, to make it easier to iterate on Python dependencies and switch between WIP PRs, I made a `requirements-<something>.txt` file and installed it at the end of my `Dockerfile` and in `.travis.yml`.  This mitigates the Python side of #1230, at least. (Afaik there isn't a similar way to mitigate the node side due to the monolithic nature of `package.json`.)
This PR is an attempt to formalize this pattern by just adding a `requirements-temp-extras.txt` to the repository, which should always be empty (save for its explanatory comments) on the `master`/`develop` branches, but which may contain modules on one's personal checkout or in WIP PRs.
> Add requirements-temp-extras.txt for easy tinkering/WIP PRs

- frontend/source/js/data-explorer/autocomplete.js
- frontend/source/js/tests/data-explorer_tests.js
Fixes #1355
In the case of `searchStr` comprising only special characters (like `"{{"`) the `while` loop in `appendHighlightedTerm` would never exit because the `sanitizedSearchString` was the empty string, so the regular expression built from it would always return a match.
The code in `autocomplete.js` is still a bit dubious, and I don't love that it is using jQuery. I bet we could could either find or write a better React autocomplete.
> Fix infinite loop case in autocomplete.js

- requirements-dev.txt
- requirements-temp-extras.txt
- requirements.txt
Oooof, I was a bit too eager to merge #1353 and did so without migrating the requirements out of `requirements-temp-extras.txt`.
This moves them into `requirements.txt`, rather than `requirements-dev.txt`, because right now we're actually serving the developer docs on production... which makes sense I guess since we're also serving the style guide on production too...
> Oops, migrate temp requirements into requirements.txt

- docs/docker.md
This removes a weird unicode character introduced in #1309. It also line wraps the lines from that PR at 80 columns because all the other lines are wrapped at that amount and I am obsessive.
> Remove weird unicode character from docker.md

- docs/api.md
- docs/deploy.md
Uggh this is an attempt to make the API docs less confusing.  I think that eventually the real solution will be to have a snazzy interactive documentation page that uses Swagger or whatever, but I guess this is hopefully good enough for now.
> Maybe make API docs less confusing

- frontend/source/sass/data_explorer.scss
Closes #1229
Closes #1371
- Increase size of contract year radio labels to `$base-font-size`, which is inline with the size of other stuff in the `.filter-block` section
- Simplify/fix negative margins on `.contract-year-item`s so that the light gray borders show properly
- Fix font size of Experience `legend`
- Adjust margins on "Optional filters" heading
- Remove extraneous `margin-bottom` and `font-size` on `.contract-year legend`
Contract Year Radios Before:
Contract Year Radios After:
Entire Filter Block Before:
Entire Filter Block After:
> Data Explorer filter styling fixes

- docker-update.sh
If `./docker-update.sh` ever fails, which it is likely to do, users (especially those new to docker) might be left feeling confused and alone.
This PR helps them out a bit by printing the following in the case of failure:
```
Alas, something didn't work when trying to update your Docker setup.
If you're not sure what the problem is, you might want to just
reset your environment by running:
docker-compose stop
docker-compose rm -v
./docker-update.sh
Note that this will reset your database! It will also re-fetch
your package dependencies, among other things, so make sure you
have a good internet connection.
```
> Show help if ./docker-update.sh fails

- data_explorer/templates/index.html
- frontend/source/js/data-explorer/explorer.js
- frontend/source/sass/components/_header.scss
Fixes #1341 by moving the Data Explorer scripts back into the document `<head>`. While this will cause (hopefully unnoticeably) more time before the page is rendered, it should get rid of weird jumps that happen due to the React app even starting to load after other DOM elements.
> Load Data Explorer React app in <head>

- hourglass/tests/tests.py
This fixes #1377 in a weird way.
> Eliminate spurious pytest warning

- requirements-dev.txt
As mentioned in https://github.com/18F/calc/pull/1384#discussion_r101420670:
> Blerg, this is a dependency of `flake8`, but flake8 implicitly gives us 1.3.0, which doesn't have https://github.com/PyCQA/pyflakes/pull/80, which fixes an incompatibility with parsing files that have f-strings in them.  So we're explicitly requiring the newer version here.
This PR doesn't add any actual f-strings, but every PR i've been working on in the past day has used them and i'm sick of pyflakes barfing on me. 😣
> Use pyflakes 1.4 for python 3.6 f-string support

- docs/deploy.md
This fixes #1361 by just removing the sandbox instructions.  Upon merging we should also delete the [wiki page](https://github.com/18F/calc/wiki/How-to-Deploy-to-your-cloud.gov-Sandbox) it links to.
I figure it's safe to delete this; the main reason it was originally written was so we could easily share experimental branches via our cloud.gov sandboxes, but now that's much more easily done through our AWS sandboxes instead.
> Remove out-of-date cloud.gov sandbox instructions

- data_capture/analysis/export.py
Fixes a bug encountered by a user of this experimental feature today. On export, they were getting an error (due to a `KeyError`) when one or more labor categories were not able to be analyzed. This PR adds a simple check to make sure the `analyzed_row` is populated (by considering the presence of the `'count'` key to mean that the rest of the fields will also be available).
> Output mostly blank row when analysis not available, fix exception

- Dockerfile.cloud-extras
- create-aws-instance.sh
- docker-compose.cloud.yml
- docs/Makefile
- docs/docker.md
- update.sh
Oops, it looks like #1369 actually broke our docker cloud deployment setup. This fixes it and also adds the `create-aws-instance.sh` script, based on the one in #997, to make it easier to deploy to docker on an aws ec2 instance.
As such, this also basically fixes #1396.
> Docker cloud fixes

- hourglass/tests/test_wsgi_middleware.py
- hourglass/urls.py
- hourglass/wsgi.py
- hourglass/wsgi_middleware.py
This is really yak shaving, but it was bugging me that `docs/` was just a redirect to `static/docs/`, so I wrote a little [WSGI](https://www.python.org/dev/peps/pep-0333/) middleware that rewrites `docs/` internally to `static/docs`.  This "fools" the underlying Django app into thinking that all requests coming in to `docs/` are actually coming in to `static/docs/`.
This is extremely low-priority, though, so feel free to just reject it and tell me to focus on more important things. 😛 
If we do decide to merge it, though, we should add tests.
> Serve docs from /docs/ instead of /static/docs/

- data_capture/templates/data_capture/panels/docs.html
Urrg #1391 removed the named `sphinx-docs` URL from the url config because the docs endpoint is now being served through underlying WSGI middleware instead of django.  This fixes things by just linking to `/docs/` directly.
> Fix broken link in djdt docs panel.

- .dockerignore
This adds some directories to our `.dockerignore` file.  While they affect the files copied into the docker image on cloud builds, they are also uploaded to the docker host when the image is built because they constitute the [build context](https://github.com/docker/docker/issues/2342).
This means that by default, everything not mentioned in `.dockerignore` is *always* uploaded to the docker host before it even starts building the docker image.
So a really big context slows things down a little bit when developing locally, but for cloud deploys it makes a really big difference, since the context is being transmitted across the intertubes. So if you have a slow internet connection, `docker-compose build` will take an eternity.
This PR reduces the size of the build context from ~70 MB to …
> Add directories to .dockerignore

- data_capture/schedules/coercers.py
- data_capture/schedules/s70.py
- data_capture/tests/test_s70.py
This replaces the simple `int` coercer for `min_experience` with a new one called `extract_first_int` that instead returns the _first_ integer value found in the cell's contents.
This will allow gleaning of contents like `"At least 5 years, with 2 years management"` (-> `5`) that @tram has been seeing in research sessions. It will also handle contents like `"10+"` (-> `10`). And it will of course handle the "normal" case of just having an integer in the cell.
We discussed wanting to have "warning messages" shown for this special gleaning case (and maybe some others), since it is possible our parser could glean an unintended or surprising value, so it would be nice to notify the user, but not throw out the row. I think implementation of these warnings should be handled separately though.
> Glean first integer in cell contents for min experience

- docs/environment.md
The really useful info on `API_HOST` is in the API docs as of #1366, so I figure we should link to that instead of the cloud foundry deployment instructions.
> Link to API docs for more details on API_HOST

- docs/environment.md
- hourglass/context_processors.py
- hourglass/settings.py
For temporary AWS sandbox deployments of CALC that contain WIP PRs, I thought it'd be nice if the banner could link to the PR, e.g.:
```bash
NON_PROD_INSTANCE_NAME="<a href='https://github.com/18F/calc/pull/997'>price list analysis</a>"
```
could display on the site as:
> ![screen shot 2017-02-23 at 8 19 38 am](https://cloud.githubusercontent.com/assets/124687/23260762/5f933216-f9a1-11e6-8929-f59d12562b19.png)
Even for our dev/staging deploys, perhaps if we eventually write up a document that explains what they are (e.g. that `dev` is the head of the `develop` branch while `staging` is pre-tagged `master`) we could link them to the explanatory document.
Wat u say @jseppi ?
> Allow NON_PROD_INSTANCE_NAME to contain HTML

- frontend/source/js/data-explorer/components/histogram.jsx
Fixes #1402
Fixed by changing all `.label`s to `.chart-label`s in histogram.jsx.
Looks like this again:
> Fix histogram label regression

- docker-compose.local.yml
- hourglass/settings.py
So one of the things I noticed while working on #1407 is that it's not easy to change `EMAIL_URL` on local development instances because the environment variables specified in `docker-compose.local.yml` override those in the user's `.env` file.
To work around this, I added a new, undocumented `DEFAULT_DEBUG_EMAIL_URL` environment variable that basically tells debug instances what email URL to use if `EMAIL_URL` isn't defined. It defaults to `console:`, just like `EMAIL_URL` did.
I'm leaving this new variable undocumented because it's really more of an implementation detail--not something that we expect devs or deployers to redefine.
This will allow devs to specify `EMAIL_URL` in their `.env` file to deliver "real" emails if they really need to test that out.
> Add private DEFAULT_DEBUG_EMAIL_URL env var

- data_capture/tests/test_email.py
- hourglass/tests/common.py
This is a workaround for https://github.com/18F/calc/pull/1407#discussion_r103016299, whereby running some tests standalone results in an `ImproperlyConfigured` error.  I guess also by enabling both the standard auth backend and the `UaaBackend`, we can move towards fixing #677.
> Include UaaBackend in tests

- styleguide/templates/styleguide.html
- styleguide/templatetags/styleguide.py
- styleguide/tests.py
@jseppi I'm not sure if this is what you meant by https://github.com/18F/calc/pull/1407#discussion_r103044659, but I thought it'd be useful regardless. Basically it adds `{% template_tag_library %}`, `{% template_url %}`, and `{% template_link %}` template tags to the styleguide, which allows us to link to templates and template tag libraries like so:
> ![template_links](https://cloud.githubusercontent.com/assets/124687/23368362/9c9867b6-fcdb-11e6-8a6e-2c04719ec47f.png)
That way anyone who wants to edit one of these can easily find the link (though it could also be discovered by using the Django Debug Toolbar, I think this is easier).
> Link to email template source in styleguide

- frontend/source/js/data-explorer/components/app.jsx
- frontend/source/js/data-explorer/components/description.jsx
- frontend/source/js/data-explorer/components/title-tag-synchronizer.jsx
- frontend/source/js/data-explorer/tests/title-tag-synchronizer.test.jsx
- frontend/source/js/data-explorer/util.js
This fixes #1315.
Note that I decided to make this a React component that doesn't actually render anything, but instead changes `document.title` whenever its `props` change.  I thought this was a decent way to encapsulate-out the functionality without e.g. bloating an existing class with it.  I also thought about making it redux middleware instead, but I currently find redux middleware a bit more confusing than react components, and besides, changing the `<title>` does *feel* like a view logic kind of thing, even if we're not literally rendering the `<title>` tag via the virtual DOM.
> Sync page <title> to name of search

- data_capture/email.py
- data_capture/management/commands/send_example_emails.py
- styleguide/email_examples.py
@jseppi I'm also not sure if this is what you meant by https://github.com/18F/calc/pull/1407#discussion_r103044659, but I thought it might be a good idea to move the metadata about example emails closer to the definition of the email sending functions.
Advantages:
* It allows us to enforce DRY a bit, by not specifying the template name in two different places.
* It should also help ensure that future emails added to the system come with built-in examples (rather than not coming with examples b/c the contributor didn't know how to add them).
Disadvantages:
* I'm not sure if I'm a big fan of the decorator approach, which is responsible for passing the template name in as the first argument to the sender function. This makes it harder to understand how to use a sender function just by …
> Move example email metadata into emails.py

- frontend/source/js/data-explorer/components/education-level.jsx
- frontend/source/js/data-explorer/components/slidey-panel.jsx
- frontend/source/js/data-explorer/components/util.jsx
- frontend/source/js/data-explorer/tests/__snapshots__/education-level.test.jsx.snap
- frontend/source/js/data-explorer/tests/education-level.test.jsx
- frontend/source/js/data-explorer/tests/slidey-panel.test.jsx
- frontend/source/sass/data_explorer.scss
- package.json
This fixes #1227 by adding a `<SlideyPanel>` component that uses [`ReactTransitionGroup`](https://facebook.github.io/react/docs/animation.html#low-level-api-reacttransitiongroup) under the hood.
If jQuery is available, it uses `$.slideUp`/`$.slideDown` to animate the panel; otherwise the transition is instantaneous. I did this because we've still got it on the page, and it's a lot easier to use than CSS transitions, which are kinda painful to do sliding animations with.
To do:
> Add SlideyPanel to make education dropdown slide up/down again

- data_capture/analysis/core.py
- data_capture/analysis/finders.py
- data_capture/tests/test_analysis.py
- hourglass/settings.py
Fixes #1452.
I got the impression that Kelly had mixed feelings about the externally-imposed rationale for #1452, so as a way to satisfy the requirements while still leaving the architecture fairly flexible (and our unit tests unbroken), I added a `PRICE_LIST_ANALYSIS_FINDERS` setting which is a list of class names to use for broadening the contract search. That way we can use the finder(s) our current clients want for this particular project, but change things up later if we want.
> List price list analysis finders in settings.py

- styleguide/templates/styleguide.html
- styleguide/templatetags/styleguide.py
This just adds more links to sources in the styleguide, to make it easier to hack on 'em when the time comes (or just learn more about them).
It also introduces `{% scss %}` and `{% js %}` template tags that make the display of paths less verbose for SCSS and JS files; while they're displayed relative to the `frontend/source/js|sass` directories, they can be followed to GitHub to learn the absolute path to them.
@hbillings what do you think of this?
> Add more links to sources in styleguide.

- docker-compose.yml
- docker-services.yml
- docker_django_management.py
This fixes #1471 by storing `/home` in a Docker volume. It also means that `pip`'s cache should be saved across `docker-compose` runs too, which is nice.
I made `/home` a docker volume instead of `/home/calc_user` because we actually want `useradd` to create the actual home directory in `docker_django_management.py`, as it will automatically copy the skeleton files into it (e.g. `.profile`, `.bashrc`), which can be helpful.
> Store /home in a Docker volume

- api/tests/test_api.py
- api/views.py
- docs/api.md
Pulled this from #1467.
This adjusts up our api to parse the `q` param in "csv-style," i.e. allowing quotation-mark-delimited individual terms within the comma-separated list. For example, the api can now handle a query like `q="Driver, Heavy Truck", Engineer` as two distinct labor category terms: `"Driver, Heavy Truck"` and `"Engineer"`.
Ref #960 and #1459
> Add API support for quote-delimited labor category param (`q`)

- api/tests/test_api.py
- contracts/models.py
Fixes #1475
The problem was that the regex in `convert_to_tsquery` was stripping out numeric characters, even though the comment right above it said that it should only strip _non_-alphanumeric chars.
> Fix convert_to_tsquery regex to accept numeric chars

- frontend/source/js/data-explorer/autocomplete.js
- frontend/source/js/data-explorer/tests/autocomplete.test.js
Closes #1484
The majority of the errors captured by New Relic in #1484 (the first two bars in the chart shown there) are due to `result` being null or undefined. This PR extracts the autocomplete result processing logic to a tested function, and guards against null/empty/undefined results.
> Guard against null or undefined result in autocomplete response handler

- gulpfile.js
This fixes the problem mentioned in https://github.com/18F/calc/pull/1481#issuecomment-285788426.
> Define NODE_ENV properly in webpack pipeline

- frontend/source/js/data-explorer/components/export-data.jsx
- frontend/source/js/data-explorer/history.js
- frontend/source/js/data-explorer/tests/util.test.js
- frontend/source/js/data-explorer/util.js
- frontend/source/js/tests/data-explorer_tests.js
Replaces our custom `parseQuery` and `joinQuery` with node's `querystring` module methods `parse` and `stringify`.
> Use querystring module in place of custom functions

- gulpfile.js
- package.json
- yarn.lock
This should make @toolness happy :)
This PR changes our `gulp` process to use Webpack 2 via `webpack-stream` to build the Data Explorer React app.
I didn't measure, but it seems **much** faster to me, both on on initial build and on subsequent watch-triggered builds. File size of the resultant bundle is also slightly smaller. 
Closes #1322
> Use webpack for data-explorer JavaScript bundle

- docker-compose.yml
The default [postgres `Dockerfile`](https://github.com/docker-library/postgres/blob/5159417968c6a08e2ed784498cba28f22a74b03e/9.6/Dockerfile) contains the following line:
```dockerfile
VOLUME /var/lib/postgresql/data
```
By default, this volume will be given a name that looks like a bunch of random hex digits.  This makes it really hard to introspect, though, and difficult to just wipe out entirely if you want to reset your db without wiping out your other calc volumes (like `node-modules` etc).
This PR names the volume `pgdata`, which means that docker-compose will call it `calc_pgdata` (assuming that your calc checkout is in a directory called `calc`).  This means running `docker volume ls` gives you something like this:
```
DRIVER              VOLUME NAME
local               calc_home …
```
> Add named 'pgdata' volume to docker-compose.yml

- requirements.txt
All the work is in https://github.com/18F/djorm-ext-pgfulltext/pull/2, this just points `requirements.txt` at it.
> Yet another alternate fix for #1498 (unwrapping approach)

- contracts/tests/test_contract.py
This just lifts the unicode contract search test from #1500, which will help ensure there's no regressions when we eventually migrate to Django 1.10's native full-text search.
> Add UnicodeContractSearchTestCase

- api/tests/test_autocomplete_api.py
- api/tests/test_rates_api.py
- api/views.py
- frontend/source/js/data-explorer/autocomplete.js
- frontend/source/js/data-explorer/tests/autocomplete.test.js
This PR limits the server-side autocomplete results to a maximum of 20 results. It also adds a few tests for the autocomplete (`/api/search`) endpoint since there were no tests at all. This will result in speed/efficiency increases for our servers and for all clients.
I don't know how to do "real" profiling, but a quick test using `"en"` as the query reduced network request time on my LOCAL dev environment from about `1.7 seconds` down to `400ms`.
Background:
While looking around through our [New Relic transaction monitoring](https://rpm.newrelic.com/accounts/987071/applications/5976077/transactions), I noticed that the autocomplete methods take kind of a long time:
I took a quick look at the code and noticed that the our autocomplete API method (at `/api/search`) returns ALL results it …
> Limit autocomplete results on server-side

- contracts/tests/test_load_data.py
I know we might be getting rid of the `load_data` command (see #1028), but since it's still around, I figured we might as well test it.  I noticed its code didn't seem to be called by the test suite when working on #1466.
This adds a simple test that runs the command on sample data, but I'm confused about something: there are 100 rows, and when running, the command says that it processed 100 rows and skipped none, yet only 79 `Contract` models have been added to the database. Why is that?
At first I thought it might be because some of the contracts might be expired, so perhaps those aren't being added to the db, but after using `freezegun` to alter the current date, it didn't seem to affect things.
@jseppi any ideas?
> Add load_data test.

- hourglass/healthcheck.py
- hourglass/tests/tests.py
Fixes #1516.
Note that once we push this to production, we'll want to change the NewRelic monitor such that it searches for the following text in responses:
```
"is_everything_ok": true
```
> Make /healthcheck/ always return 200

- data_capture/schedules/base.py
- docker_django_management.py
- frontend/tests/sauce_connect.py
- mypy.ini
- requirements.txt
This upgrades us to mypy 0.501.
* `silent_imports` has been replaced by `ignore_missing_imports=True; follow_imports=skip`
* Previously, annotations specified in comments auto-imported built-in typings like `Dict` and `List`, but this is no longer the case, so we have to import them explicitly.
The biggest hassle here is actually just the fact that mypy changed its pypi entry from `mypy-lang` to `mypy`: this means that when you run `pip install -r requirements.txt` (or `./update.sh`) it will actually install `mypy` *on top of* `mypy-lang`.  By itself, this isn't horrible, because the `mypy` CLI will overwrite the command of the same name provided by `mypy-lang`.
However, what *does* suck is that if you switch back to a different branch that *doesn't* use this new version of mypy, running …
> Upgrade to mypy 0.501

- docs/environment.md
- gulpfile.js
This fixes #1511 by not running eslint every time a file changes if `ESLINT_CHILL_OUT` is set.
> Don't eslint on file change if ESLINT_CHILL_OUT is set

- .travis.yml
From the cloud.gov newsletter, we should be using [v6.25.0](https://github.com/cloudfoundry/cli/releases/tag/v6.25.0)
> Upgrade cf cli in Travis to latest recommended version

- docs/environment.md
- hourglass/settings.py
- hourglass/site_utils.py
- hourglass/tests/test_site_utils.py
This adds a new setting, `DEBUG_HTTPS`, which allows the site to be served in debug mode over HTTPS.
It's primarily of importance to the site's notion of its "canonical url" when no `request` object is present: until now, we've always assumed that if `DEBUG` is true, the protocol for the canonical URL should be `http`, but setting `DEBUG_HTTPS` essentially forces it to be `https`.
I needed to add support for this to #997 because we're now putting the price list analysis deployment behind cloud.gov's SSL-terminating reverse proxy, and I figured this kind of functionality might be useful for local development too.
> Add DEBUG_HTTPS setting

- .travis.yml
- docs/monitoring.md
Closes #1331 
Ref #1521
This PR sets up Travis to run `py.test production_tests` when it is doing its daily cron run.
To Do:
> Run production_tests when in travis cron

- hourglass/settings.py
- hourglass/urls.py
This enables [the Django admin documentation generator](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/admindocs/) on development (`DEBUG`) instances of CALC.
It adds a "Documentation" option under the site admin:
> ![admindocs](https://cloud.githubusercontent.com/assets/124687/23462787/45897752-fe5d-11e6-9f2d-b93e94149de5.png)
And as can be seen from the above screenshot, it links to auto-generated documentation on template tags and filters, models, and views.
Since our Django admin skin wasn't created to take this kind of content into consideration, though, the styling on the individual pages isn't that great.  For example, while I *think* the tags and filters docs are supposed to have a right-hand TOC sidebar that lists all the tags and filters, it shows up at the very bottom …
> [WIP] Enable django.contrib.admindocs in DEBUG mode

- requirements.txt
Closes #1526
Security release notes: https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
> Upgrade to Django 1.9.13

- hourglass/templates/admin/base.html
- requirements.txt
- styleguide/views.py
This PR *prepares* CALC for migration to Django 1.10--by which I mean that it makes low-impact, backwards-compatible changes to ensure that CALC's test suite passes on Django 1.10, but it doesn't actually *upgrade* CALC's version of Django. This is because we're about to put CALC on hiatus and might not be able to address any problems that might arise from actually migrating. But we do want to make it *easy* to migrate if we (or another team that inherits this project) need to upgrade once Django 1.9 reaches end-of-life. This will make it easier to eventually make our way to 1.11 (#1346), which is the next long-term support (LTS) release.
This is coupled with the changes made in our fork of djorm-ext-pgfulltext at https://github.com/18F/djorm-ext-pgfulltext/pull/3, so if we merge this PR, …
> Prepare CALC for migration to Django 1.10

- cf.sh
- contracts/models.py
- data_capture/admin.py
- update.sh
Fixes #1546 
- Updates all `update_search_field` calls to include `Contract` as the `"model"` arg
- Adds `set -e` to `cf.sh` so that it will properly fail deployments when a subcommand has an error
- Unrelated change: Minor code cleanup suggested by @cmc333333 to move the `list_display` fields of `CustomUserAdmin` in `data_capture/admin.py` up to the class definition instead of in the constructor. Don't know what I was thinking there 😝 
Note that I thought about modifying our shadowed `update_search_field` to itself add the model param into the `kwargs` that get passed to the original `update_search_field`, but thought that was a little too whacky.
> Fix update_search_field args

- requirements.txt
This is an alternative fix for #1546 that modifies our fork of djorm-ext-pgfulltext to use a fix for the regression that caused #1546 (whereby `model` became a required arg instead of an optional one), which was done in https://github.com/18F/djorm-ext-pgfulltext/pull/3/commits/7ce6606dcb2c4fdd235439b6adcadeb143974a62.
Note that this isn't mutually exclusive from #1547, since that PR just explicitly passes `model` in as an arg. I think this fix is nice because it keeps our fork of djorm-ext-pgfulltext still working the same way as it always has, though.
> Use updated djorm-ext-pgfulltext

- frontend/source/js/data-explorer/components/query-type.jsx
- frontend/source/js/data-explorer/tests/__snapshots__/query-type.test.jsx.snap
- frontend/tests/axe.py
- frontend/tests/test_selenium.py
- package.json
- yarn.lock
This introduces the [aXe accessibility testing tool](https://www.deque.com/products/axe/) to CALC's testing regimen by running it on the data explorer. Right now we're ignoring the handful of color contrast issues on the page because I'd like a designer's help fixing those and I just wanted to focus on introducing aXe for now.
The one violation I *did* fix is in regards to the fact that the radios under the labor category search weren't grouped in an accessible way.
> Run aXe-core on data explorer, fix a11y violation.

- update.sh
I was having trouble following calc's installation instructions with python 3.6.  So I am updating the install script from:
pip install -r requirements.txt
to
python -m pip install -r requirements.txt 
So that I can install things.
> adding to update.sh so that things will work with 3.6

- api/tests/test_rates_csv.py
- api/views.py
The raw query string is written to the CSV export of price search results.
If the query starts with excel formula characters, then when the CSV
is opened in Excel, lots of (potentially bad) stuff can happen as Excel
processes the formula. This PR mitigates this issue by prefixing the query
string with an apostrophe if it starts with an Excel formular character.
That way, Excel will treat the cell content as plain text rather than a formula.
ref: https://github.com/18F/vuln-reports-private/issues/8
> Prefix excel formula chars with apostrophe in query csv export text

- .circleci/config.yml
- docs/release.md
- Update `release.md` to follow new 3-tiered branch-based deployments (`develop`, `staging`, and `master`)
- Use double square brackets because they behave a little nicer in bash
- use `DEPLOY_ENV=prod` for prod deploy (it was erroneously set to `staging` previously)
I also created a new `staging` branch in the repo, branched off the current `master` branch. I setup branch protection and a required CircleCi build status check, like we have on `master` and `develop`.
This deployment process change is necessary because CircleCI doesn't work off of tags like Travis does (we used to use a version tag to trigger production releases).
> Switch to 3-tiered branch deployments

- data_capture/models.py
- data_capture/tests/test_models.py
- fix #1578
- show status text instead of code
- add tests to check that logging is happening when pl status changes
> improve pricelist status logging and add tests

- hourglass/settings.py
and only allow read-only methods (GET and OPTIONS).
Fixes #1583.
> restrict CORS to /api/ routes

- docs/release.md
I think this is due to the changes we recently made when switching to a branch release model instead of a tag-based one. Basically, the text says to issue a PR against `staging` but the PR link actually creates a PR against `master`.
> Fix PR link in docs/release.md

- hourglass/middleware.py
- hourglass/tests/tests.py
> Add 'Cache-Control: no-cache' for /admin/ routes

- docker-compose.local.yml
Adds the `delegated` flag to the `.:/calc` mounted volume in `docker-compose.local.yml`.
This should speed up things that rely on filesystem operations (like running tests) during local development.
> Use delegated volumes in local docker-compose config

- Dockerfile
- docs/setup.md
- hourglass/tests/test_configuration.py
- runtime.txt
`3.6.2` is no longer supported on cloud.gov. This upgrades us to the most recent version that is supported.
closes #1628
> Upgrade to python 3.6.4

- Dockerfile
- docs/setup.md
- hourglass/tests/test_configuration.py
- runtime.txt
Closes #1630. See issue for details.
> Specify Python at minor version instead of patch

- docs/deploy.md
Add information on CALC's use of the cloud.gov Identity Provider Service for getting UAA OAuth credentials.
> add docs on use of identity provider service

- hourglass/settings_utils.py
- hourglass/tests/tests.py
Missed this change in #1642. We need to look for a VCAP service with the "redis32" identifier when constructing our `REDIS_URL`. This should fix the currently failing `calc-dev` deployments.
> Use "redis32" for vcap service name

- manifests/manifest-dev.yml
- manifests/manifest-prod.yml
- manifests/manifest-staging.yml
This should make it so our service instances are automatically bound to each Cloud Foundry app in each space.
Previously, service instances were manually bound and would have to be manually re-bound if they were disconnected. This change makes it so the binding is enforced with each deployment.
> Add app-level service bindings in each manifest

- .circleci/deploy-circle.sh
Adds specific `cf push`es for our `rqscheduler` and `rqworker` during deployments from CircleCI.
> Deploy worker and scheduler apps from CI

- cf.sh
- contracts/apps.py
- contracts/loaders/schedule_70.py
- contracts/management/commands/load_data.py
- contracts/management/commands/update_search_field.py
- contracts/migrations/0001_initial.py
- contracts/migrations/0010_auto_20150529_1956.py
- contracts/models.py
- contracts/signals.py
- contracts/tests/test_contract.py
- data_capture/jobs.py
- docs/environment.md
- hourglass/settings.py
- requirements.txt
- update.sh
This fixes #1645.
Implementing the fix involved some reading of [`djorm_pgfulltext`'s source code](https://github.com/18F/djorm-ext-pgfulltext/), as well as of [`django.contrib.postgres.search`](https://docs.djangoproject.com/en/2.0/_modules/django/contrib/postgres/search/).  A few things djorm-ext-pgfulltext made easy aren't supported out-of-the-box by Django's full-text-search, so I had to implement a solution.
* `manage.py update_search_field` no longer delegates to a `djorm_pgfulltext` command.  It was easier to just hard-code the auto-updating of the `Contracts` model, so I removed the `<app-name> <model-name>` arguments to the command.
* Doing this work required examining the underlying SQL Django was sending to the database.  Hacking this into `settings.py` was cumbersome, so I …
> Remove djorm-exp-pgfulltext

- .cfignore
- .circleci/config.yml
- .dockerignore
- .gitignore
- frontend/source/js/data-explorer/tests/__snapshots__/business-size.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/contract-year.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/description-filter.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/description.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/education-level-item.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/education-level.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/experience.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/export-data.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/highlights.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/labor-category.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/loading-indicator.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/proposed-price.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/query-type.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/schedule.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/site.test.jsx.snap
- frontend/source/js/data-explorer/tests/__snapshots__/tooltip.test.jsx.snap
- package.json
- yarn.lock
This PR adds combined test coverage reporting of our Jest tests (for the Data Explorer React code) with our py.test tests.
- upgrade `jest` version
- also update all component snapshots since they render slightly differently (basically just formatting) with this new version
- add `coverage/` to ignore-dotfiles
- add jest config to `package.json`
Closes #1439
> Combine jest and python coverage reporting

- .gitignore
- docs/Makefile
- docs/changelog.md
- gulpfile.js
Right now our `docs` directory contains `changelog.md`, which is a symlink to the changelog in our repo's root directory.  However, symlinks aren't easily supported across current versions of Windows, which means the docs build, but not with the changelog in them (and with loads of annoying error output complaining about it).
This fixes things so that the changelog gets copied over to the `docs` directory at build time.  It also watches the changelog in the root directory, so that if that changes, the Sphinx docs are rebuilt (I don't think the watch logic accounts for this).
> Ensure sphinx docs build on Windows without errors, and rebuild docs when changelog changes

- frontend/source/js/data-explorer/components/proposed-price.jsx
- frontend/source/js/data-explorer/tests/__snapshots__/proposed-price.test.jsx.snap
- hourglass/settings_utils.py
Using `type="button"` obviates the need to call `e.preventDefault()` on that button's click handler.
Also make a slight unrelated modification to `is_running_tests()` to return `True` when `py.test` is called as `pytest` (no period).
Closes #1515
> Add `type="button"` to ProposedPrice's "Go" button

- .circleci/config.yml
This is an experiment to see if CircleCI can reliably run selenium tests with PhantomJS.  As far as I can tell, it was only Travis that had problems in #330 (I was unable to reproduce the errors locally), so we might have better luck with Circle.
> Attempt to run Selenium tests on CircleCI.

- .eslintignore
When running `eslint` I noticed it started spewing all kinds of errors about files in the `coverage` directory, which I think was added in #1653 when we enabled jest coverage reporting.  So this adds that directory to our `.estlintignore`.
> Add 'coverage' dir to .eslintignore

- data_capture/r10_spreadsheet_converter.py
When attempting to diagnose #1601, I noticed that an inordinate amount of time was being spent in [`xlrd.open_workbook()`](http://xlrd.readthedocs.io/en/latest/api.html#module-xlrd)--as in, upwards of 2 minutes for Kelly's region 10 XLSX from October 2017, which has around 57,000 rows.  Then I realized that we are making multiple calls to this function during region 10 upload jobs.
This improves the situation by caching the result of the call, which seems to speed up r10 bulk upload by 2-4 minutes.
It's also possible this might help with the memory issue mentioned in #1601, but I'm not sure.  If we really want to reduce memory usage _and_ speed things up, we might want to require Kelly to upload a CSV instead of an XLSX: my guess is that whatever Microsoft tool he's using on his end will …
> Cache XLSX workbook in Region10SpreadsheetConverter.

- .circleci/config.yml
- .eslintignore
- frontend/source/js/common/dap-hacks.d.ts
- frontend/source/js/common/dap-hacks.js
- frontend/source/js/common/usermenu.js
- meta/management/commands/ultratest.py
- package.json
- tsconfig.json
- yarn.lock
This is an attempt to fix #1527 by using [TypeScript's `--checkJs` mode](https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files), which allows us to type-check JS files without needing to integrate TypeScript into our static asset build pipeline (to strip out type information).  It's basically a much more powerful alternative to eslint (well except for the part of eslint that overlaps with prettier).
There are reasons this could be a bad idea, though, so feel free to criticize and close this PR unmerged.
Right now we just type-check two JS files, `dap-hacks.js` and `usermenu.js`.
* Use of TypeScript's `--checkJs` mode doesn't prohibit us from actually using "real" TypeScript in the future. I just thought this might be a quick, easy way to dip our toes into TypeScript. …
> Use TypeScript's checkJs functionality on whitelisted files

- .circleci/config.yml
- CONTRIBUTING.md
- docs/frontend.md
- docs/setup.md
- frontend/tests/utils.py
- gulpfile.js
- meta/management/commands/ultratest.py
- package.json
We switched to `yarn` a while back but didn't update various docs and tooling to use it in place of `npm` or `npm run`.
Closes #1541.
> Use `yarn` instead of `npm run` everywhere

- hourglass/settings.py
- requirements.txt
`dj-email-url` v0.1.0 [(changelog)](https://github.com/migonzalvar/dj-email-url#010---2018-03-24) automatically sets `EMAIL_USE_TLS` setting when using the `submission:` "protocol" in the email connection string. This setting is required for `STARTTLS`, which is what we need for use with Amazon SES.
> Upgrade `dj-email-url` for easy TLS email connections

- docs/api.md
Part of #1698.
This is a fairly quick review and revision of `api.md`. I removed manual line-wrapping because I think it makes diff-ing less intelligible.
I think we should (later) scrap most of the contents of this file and instead use Django Rest Framework's documentation capabilities to generate API docs from the actual methods and docstrings. I'll add this idea to #1698 as well.
> Revise api.md

- frontend/source/sass/admin/changelists.scss
- frontend/source/sass/admin/overrides.scss
- frontend/source/sass/components/_buttons.scss
- frontend/source/sass/components/_labels.scss
- frontend/source/sass/components/_tables.scss
- frontend/source/sass/components/_usermenu.scss
There were a bunch of `4px` border radius settings that were hardcoded because our `$border-radius` variable used to be zero. This fixes 'em. 
Closes #1426.
> Remove hardcoded border radius 

- data_capture/jobs.py
- data_capture/management/commands/process_bulk_upload.py
- data_capture/tests/test_management_commands.py
This potentially fixes #1712 by chopping up the insertion of new contracts into batches of 5000 labor categories each.  It also reduces the lifetime of the `Region10SpreadsheetConverter` instance, so that it won't be around anymore when search indexes are updated.
While I wasn't able to definitively profile memory usage in #1601, I'm hoping that this sufficiently reduces memory usage to the point that our rq_workers don't crash anymore.
This PR also brings in the `process_bulk_upload` management command from #1601 to make future manual testing and profiling easier.
Note that this PR doesn't have ideal test coverage.  I don't want to write tests if this doesn't actually fix #1712, so I'm going to hold off on writing them until we actually try this out on cloudfoundry.
Here's example log …
> Process bulk uploads in batches

- data_explorer/templates/about.html
- frontend/source/sass/components/_page.scss
- hourglass/templates/admin/base.html
Closes #1741.
Some card classes were not in the correct DOM order, leading to double underlines.
> Fix double underline on card footer

- data_explorer/templates/_header.html
Instead of setting the columns on the `a` tag, which leads to a too-large focus ring, set them on a div that contains the `a` tag.
> Fix the focus ring around the logo

- .circleci/deploy-circle.sh
This should prevent failed deploys when the targeted `$APP_NAME` does not already exist.
> Only call `cf scale` when app exists

- docs/testing.md
- frontend/tests/test_selenium.py
For some reason, on local dev instances (but strangely not CircleCI) instantiating a WebDriver instance more than once during a test run caused a socket timeout.  This appears to fix things, at least on my machine, by keeping one long-lived WebDriver instance around for the whole test run, and shutting it down when the process exits.
To try it out without running the whole test suite, try:
```
pytest frontend/tests/test_qunit.py data_capture/tests/test_integration.py frontend/tests/test_selenium.py
```
> Keep a long-lived WebDriver instance through the whole test run

- gulpfile.js
- package.json
- yarn.lock
ref #1777 
Adds a stream `'error'` event handler to the `sass` task that will cause the build to exit with a non-zero status code when a sass error occurs during a non-watched build.
This is nice for CI because builds will fail faster and the cause of the failure will be more easily visible in the CircleCI logs.
> break non-watched builds on sass error; upgrade gulp-sass

- data_capture/jobs.py
- data_capture/r10_spreadsheet_converter.py
- requirements-dev.txt
Fixes #1788 
Updates CALC to the latest `flake8` and `pyflakes`.
Fixes two flake8 errors around the use of bare `except` statements.
> upgrade flake8/pyflakes; fix bare exceptions

- hourglass/templates/admin/search_form.html
Fixes #1726.
It took me a _really_ long time to figure out what was wrong.  At first I started comparing our `search_form.html` to [Django 1.11's](https://github.com/django/django/blob/stable/1.11.x/django/contrib/admin/templates/admin/search_form.html) and didn't notice anything different.  Then I started fiddling with our custom `UserAdmin` subclass, to no avail.  Then I just started deleting stuff, slowly reverting our custom Django admin back to the default one.
The user search field started working again when I _deleted_ `search_form.html`, which made Django fall back to the default one.  Which was weird, because that was the first thing that I'd looked at.  But it wasn't until I looked _really_ closely that I noticed that our search field had _two_ `name` attributes!  Oof.
> Fix admin user search

- .bandit
- .eslintignore
- .flake8
- api/pagination.py
- api/tests/test_docs.py
- api/urls.py
- api/views.py
- data_capture/__init__.py
- meta/management/commands/ultratest.py
- package.json
- pytest.ini
- requirements-dev.txt
- requirements.txt
This attempts to implement the solution suggested by @jseppi in https://github.com/18F/calc/issues/1698#issuecomment-378401583, whereby we use [DRF's built-in support for API documentation](http://www.django-rest-framework.org/topics/documenting-your-api/).
Specifically, it adds an endpoint at `/api/docs/` that looks like this:
> ![api-docs](https://user-images.githubusercontent.com/124687/38961837-6c57dcd6-4338-11e8-91dc-8be68af16521.png)
Clicking the "INTERACT" button brings up a modal that allows users to tinker with a specific API endpoint:
> ![interact](https://user-images.githubusercontent.com/124687/38961877-aa3218e6-4338-11e8-8854-ae7771bf2767.png)
* It seems like DRF has embraced something called [Core API](http://www.coreapi.org/), which is "a format-independent Document Object …
> Attempt to document API via Django REST Framework / Core API

- frontend/source/js/common/usermenu.js
Modifies the behavior of the header user menu to hide not only on click of its trigger link, but also on click of anywhere outside of its descendants.
Part of the tweaks requested in https://github.com/18F/calc/issues/1708 cc @ericronne
> Hide the usermenu on outside click

- .flake8
- api/tests/test_rates_api.py
- contracts/models.py
- data_capture/schedules/base.py
- data_capture/schedules/coercers.py
- data_capture/schedules/registry.py
- data_capture/signals.py
- data_capture/tests/test_forms.py
- data_capture/tests/test_integration.py
- data_capture/tests/test_models.py
- data_capture/tests/test_price_list_replace_views.py
- data_capture/tests/test_price_list_upload_views.py
- data_capture/tests/test_schedules_registry.py
- data_capture/views/price_list_replace.py
- data_capture/views/price_list_upload.py
- hourglass/changelog.py
- hourglass/tests/test_changelog.py
- meta/management/commands/bump_changelog.py
- setup.cfg
- slackbot/bot.py
From the beginning of CALC II, we knew that we'd want to support multiple schedules, so we built this into the architecture.  However, the architecture could use a bit more documentation/explanation, so I've added some here, via comments, docstrings, and type annotations.  I've also simplified a few things to make them easier to maintain in the future.
Other notes:
* I went ahead and changed the maximum line length from 80 characters to 100, as per #1818.
* When we first wrote some of this code, we were using python 3.5, not 3.6.  In this PR I've updated some of our type annotations to use [python 3.6 variable annotations](https://docs.python.org/3/whatsnew/3.6.html#pep-526-syntax-for-variable-annotations) instead of `# type:` comments.
* It seems flake8 / pycodestyle doesn't quite have …
> Improve data capture schedule documentation

- .gitignore
- docs/Makefile
- docs/index.rst
- gulpfile.js
Linking to `CHANGELOG.md` from the Sphinx docs has always been weird and added complications to our build system (see e.g. #1658).
But I realized that since we have a snazzy version of it at `/updates/` (especially since #1816) so we can just link to that (like we link to `/styleguide/` and `/api/docs/`) instead of doing extra complicated stuff with `CHANGELOG.md`.
Additionally, I _think_ this might resolve some issues I've been having whereby running tests while having `docker-compose up` running in a separate terminal sometimes makes things explode.
Note also that after merging this PR, folks might have a `docs\CHANGELOG.md` file lying around their system that `git status` complains about. This can be deleted.
> Link to /updates/ from sphinx docs

- docs/environment.md
- gulpfile.js
- meta/management/commands/ultratest.py
- package.json
- yarn.lock
In the spirit of [aggressively rolling back eslint](https://github.com/18F/calc/pull/1852), this disables eslint when compiling JS, for the reasons outlined in #1511.  If folks want to see live eslint feedback during development, it's better for them to use an editor plugin than wait upwards of 10 seconds for gulp to annoy them. Note that `ultratest` _does_ still run eslint, so it's still part of our test suite.
I believe this also shaves a few seconds off our test suite, because until now we were actually running eslint _twice_: once during compilation of the JS, and again during a separate linting phase.
> Don't lint as part of JS compilation

- styleguide/fullpage_example.py
- styleguide/templates/styleguide_fullpage_example.html
- styleguide/templates/styleguide_fullpage_example_iframe.html
- styleguide/templates/styleguide_fullpage_examples/card-collapse-header.html
- styleguide/templates/styleguide_fullpage_examples/card-footer.html
- styleguide/templates/styleguide_fullpage_examples/card-skinny.html
- styleguide/templates/styleguide_fullpage_examples/card.html
- styleguide/templatetags/styleguide.py
- styleguide/tests.py
This enhances the full-page examples in the style guide:
* They can now use template tags. However, in order to accomplish this, I had to make the files in `styleguide/templates/styleguide_fullpage_examples` regular templates, rather than purely HTML files (which actually makes more sense, since they are in the `templates` directory). A full-page example that once contained this HTML:
```html
<p>boop</p>
```
now looks like this:
```html
{% extends "styleguide_fullpage_example.html" %}
{% block body %}
{# BEGIN SNIPPET #}
<p>boop</p>
{# END SNIPPET #}
{% endblock %}
```
This certainly looks less readable, but it's also more powerful. The `{# BEGIN SNIPPET #}` and `{# END SNIPPET #}` tell the styleguide where the beginning of the HTML source it should show to readers is (if they're not …
> Allow fullpage examples to use template tags, optionally hide their HTML

- .codeclimate.yml
- docs/ci.md
- docs/index.rst
- setup.cfg
This adds documentation for our continuous integration tools, CircleCI and Code Climate.
(Ok, technically Code Climate might not be a CI tool, I'm not sure, but for our purposes I'm treating any of the third-party services listed under the "checks" section of our GitHub PRs to be CI tools.)
This also fixes #1839 by documenting how to disable some of CALC's funky tests.
It also simplifies our Code Climate configuration by:
* Removing `pep8`. This was originally added in #322, before `ultratest` existed. But once `ultratest` was added in #379, running the linter on CC became redundant.
Not only that, it actually uses a subtly different command-line tool than we do--and one that is more out-of-date than ours--which makes it hard to anticipate or reproduce its errors locally.
As if that …
> Add continuous integration docs, simplify code climate config

- frontend/source/sass/components/_buttons.scss
Against #1905, not develop
Closes #1952 for link buttons.
I also noticed that active states for secondary buttons is off. @ericronne, should I fix this while I'm at it?
> Fix button active states

- package.json
- yarn.lock
Fixes #1976.
So the problem responsible for #1976 was fixed by https://github.com/d3/d3-timer/pull/23.
A challenge here is that we don't use that package, d3-timer, directly; we use d3-transition, which specifies that it needs `d3-timer@1`, which I think means "anything that is version 1".  Until now it was using 1.0.5, which does not include the aforementioned PR.
This PR is the result of running `yarn upgrade d3-timer@1`, which changes the version of d3-timer used by d3-transition. Apparently it also adds d3-timer to our `package.json` too, I guess.
> Upgrade d3-timer to 1.0.7.

- Dockerfile
This fixes #1964 by just downloading whatever the latest version of Chrome and ChromeDriver are at the time that the `Dockerfile` is run.
I don't particularly like this approach because it means that running the `Dockerfile` won't consistently reproduce the same runtime environment for CALC and its tests: one person's `app` container might be using Chrome 66, while another developer's might be using Chrome 95, and this could end up causing confusion. But it seems like the only way to solve the problem that doesn't involve constantly babysitting the `Dockerfile` to use a valid, still-available version of Chrome and a compatible ChromeDriver version.
> Use latest Chrome, ChromeDriver in Dockerfile

- frontend/source/sass/components/_inputs.scss
- frontend/source/sass/data_explorer.scss
Closes #1975.
- Fixes focus ring on tab around Education button.
- Adds back focus on contract year. Note that this is funky because the markup here is _super_ odd.
On click it looks like:
But on tab it looks like:
This is because it's actually two different elements getting focus at different points, and I don't know how to reconcile the styles. >_<
To do:
Not doing:
- Fixing the tab focus on the slider handles. Because this is a component we're rendering from a library, we don't have much control over it, and nothing I've tried (mostly around `tabindex`) manages to take it out of the tab flow.
> Fix accessibility regressions

- frontend/source/sass/data_explorer.scss
Was `$color-blue-darker`, should've been `$color-blue-dark`
> Fixes color of selected filter options

- requirements.txt
I recently published django-uswds-forms to PyPI, so this modifies our `requirements.txt` to install it from there, rather than via git.  It's the exact same code (only some documentation has changed).
> Install django-uswds-forms via PyPI

- frontend/source/js/common/ga.js
- frontend/source/js/tests/ga_tests.js
Fixes #2005, explanations are in the comments of the PR.
> Fix ga.trackInterestingLink() on IE11

- docs/release.md
This fixes #2014 and also makes a few additional changes:
* We now tag the release separately from pushing to production, which reduces the possibility of the [tag not being pushed](https://github.com/18F/calc/issues/2014#issuecomment-398023043) and also explicitly makes clear exactly what the tagging process is doing (i.e., making the tag show up on the release page).
* We no longer wait for CircleCI before changing `version.py`. Instead, we only wait for review approval from stakeholders, and wait for CircleCI only after the final commit to change `version.py` has been made. This results in less waiting around for CircleCI to finish.
So even though the release instructions now include one additional step, the process should actually go faster and be less error prone, I think.  We'll …
> Revise release documentation

- calc/templates/admin/base.html
- data_explorer/templates/_head_meta.html
- data_explorer/templates/base.html
so it's easier to remember to use it everywhere
> Moved main.css into head_meta

- requirements-dev.txt
Bandits everywhere
Even integration tests
So we must roll back.
We should fix the issues 1.5.0 is reporting later.
> Lock bandit version to temporarly avoid issues with 1.5.0 version.

- frontend/source/js/data-explorer/components/query-type.jsx
- frontend/source/js/data-explorer/constants.js
- frontend/source/js/data-explorer/tests/__snapshots__/query-type.test.jsx.snap
- frontend/source/js/data-explorer/tests/query-type.test.jsx
- frontend/source/js/data-explorer/tests/serialization.test.js
In #2061, we removed the `match_phrase` option, but we never updated the UI to reflect that. This does that + updates the tests to match (and it sets us up nicely to move to the "exact match" checkbox design we're doing next).
> Update search UI to reflect search API changes

- frontend/source/sass/components/_forms.scss
- frontend/source/sass/data_explorer.scss
Changes:
- Added space below "Search CALC" header
- Reduced padding in selector in order to make its height match the search box
- Lightened the selector-list-item default text color a notch, for better contrast with the selected option (because sketch does a better job representing colors than chrome does!)
- Other vertical spacing adjustments
> Style refinements for the 2084 search ui work

- frontend/source/js/data-explorer/components/results-table/index.jsx
- frontend/source/js/data-explorer/components/results-table/sortable-data-cell.jsx
- frontend/source/js/data-explorer/components/results-table/vendor.jsx
- frontend/source/sass/data_explorer.scss
> Combine vendor and contract columns

- api/tests/test_rates_api.py
- contracts/models.py
Vendors have ids
Also, they often have names.
Those should be useful.
This adds to the API the ability to search by `vendor_name` or `idv_piid`. It's a naive implementation, but it might be enough—I'm not sure what the longer-term requirements are.
The tests are also fairly basic.
> Add working basic search by vendor_name or idv_piid, plus simple tests.

- data_capture/templates/data_capture/bulk_upload/region_10_step.html
- data_capture/templates/data_capture/replace_price_list/replace_step.html
In attempting to fix #2114, I realized the bulk upload templates never got updated to reflect the work done to rejigger the `head_meta` block for price list upload templates. This just removes the old block tags that are no longer applicable (and showed up oddly at the very top of the page, as seen in #2114).
> Remove template tags that are no longer used

- frontend/source/sass/components/_forms.scss
The new search-selector design failed to account for the longer list of schedules which we have on the live site (dev has 9, prod has 13). Since the selector and the highlights block share a common background color, they visually fuse:
So I added a border to the bottom of the expanded selector:
> Adds a bottom border to search selector
